#!/usr/bin/env bash
# GRUB2 discovery and transactional persistent kernel selection.
# This file is sourced by commands/system/kernel.sh after KERNEL_MANAGED_MARKER
# and the common command helpers have been defined.
# shellcheck disable=SC2004,SC2016,SC2034

KERNEL_GRUB_SUPPORTED=0
KERNEL_GRUB_REASON='尚未检测'
KERNEL_GRUB_DEFAULT_RELEASE=''
KERNEL_GRUB_NEXT_RELEASE=''
KERNEL_GRUB_DEFAULT_ID=''
KERNEL_GRUB_NEXT_ID=''
KERNEL_GRUB_DEFAULT_SELECTOR=''
KERNEL_GRUB_NEXT_SELECTOR=''
KERNEL_GRUB_CFG=''
KERNEL_GRUB_ENV=''
KERNEL_GRUB_DEFAULT_FILE=''
KERNEL_GRUB_DEFAULT_DIR=''
KERNEL_GRUB_DROPIN=''
KERNEL_GRUB_BACKUP_ROOT=''
declare -gA KERNEL_GRUB_ENTRY=()

declare -gA _KERNEL_GRUB_RELEASE_BY_ID=()
declare -gA _KERNEL_GRUB_RELEASE_BY_NUMBER=()
declare -gA _KERNEL_GRUB_RELEASE_BY_TITLE=()
declare -gA _KERNEL_GRUB_EXACT_ENTRY=()
declare -gA _KERNEL_GRUB_ID_BY_NUMBER=()
declare -gA _KERNEL_GRUB_ID_BY_TITLE=()
_KERNEL_GRUB_ACTIVE_ROOT=''

kernel_grub_init_paths() {
    KERNEL_GRUB_CFG="$(vps_cmd_system_path /boot/grub/grub.cfg)" || return $?
    KERNEL_GRUB_ENV="$(vps_cmd_system_path /boot/grub/grubenv)" || return $?
    KERNEL_GRUB_DEFAULT_FILE="$(vps_cmd_system_path /etc/default/grub)" || return $?
    KERNEL_GRUB_DEFAULT_DIR="$(vps_cmd_system_path /etc/default/grub.d)" || return $?
    KERNEL_GRUB_DROPIN="$(vps_cmd_system_path /etc/default/grub.d/99-vpsctl-kernel.cfg)" || return $?
    KERNEL_GRUB_BACKUP_ROOT="$(vps_cmd_system_path /var/lib/vpsctl/system/kernel/backups)" || return $?
}

kernel_grub_probe_active() {
    local output package
    local grub_common=0 grub_pc=0 grub_efi=0

    [[ -f "$KERNEL_GRUB_CFG" && ! -L "$KERNEL_GRUB_CFG" && -r "$KERNEL_GRUB_CFG" ]] || {
        KERNEL_GRUB_REASON='未找到可读的标准 /boot/grub/grub.cfg'
        return 1
    }
    grep -Eq '^# DO NOT EDIT THIS FILE|grub-mkconfig' "$KERNEL_GRUB_CFG" || {
        KERNEL_GRUB_REASON='grub.cfg 不具有发行版 grub-mkconfig 生成标记'
        return 1
    }
    if ! command -v update-grub >/dev/null 2>&1 || ! command -v grub-editenv >/dev/null 2>&1; then
        KERNEL_GRUB_REASON='缺少 update-grub 或 grub-editenv，无法安全维护 GRUB2'
        return 1
    fi
    command -v dpkg-query >/dev/null 2>&1 || {
        KERNEL_GRUB_REASON='无法确认发行版 GRUB 软件包状态'
        return 1
    }
    output="$(LC_ALL=C dpkg-query -W -f='${db:Status-Abbrev}\t${binary:Package}\n' \
        grub-common grub-pc grub-pc-bin grub-efi-amd64 grub-efi-amd64-bin 2>/dev/null || true)"
    while IFS=$'\t' read -r status package; do
        [[ "$status" == 'ii ' || "$status" == 'hi ' ]] || continue
        case "${package%%:*}" in
            grub-common) grub_common=1 ;;
            grub-pc) grub_pc=1 ;;
            grub-efi-amd64 | grub-efi-amd64-bin) grub_efi=1 ;;
        esac
    done <<<"$output"
    ((grub_common == 1)) || {
        KERNEL_GRUB_REASON='未确认 grub-common 已安装'
        return 1
    }

    if [[ -d "$(vps_cmd_system_path /sys/firmware/efi)" ]]; then
        ((grub_efi == 1)) || {
            KERNEL_GRUB_REASON='检测到 UEFI，但未确认 GRUB EFI 后端软件包已安装'
            return 1
        }
        _kernel_grub_probe_efi_bootcurrent || return 1
    else
        ((grub_pc == 1)) || {
            KERNEL_GRUB_REASON='BIOS 模式下未确认完整 grub-pc 软件包已安装'
            return 1
        }
        [[ -f "$(vps_cmd_system_path /boot/grub/i386-pc/normal.mod)" ]] || {
            KERNEL_GRUB_REASON='BIOS 模式下未确认实际 i386-pc GRUB 模块布局'
            return 1
        }
    fi
    return 0
}

_kernel_grub_probe_efi_bootcurrent() {
    local output current line active_line='' loader lower_loader loader_path
    command -v efibootmgr >/dev/null 2>&1 || {
        KERNEL_GRUB_REASON='检测到 UEFI，但缺少 efibootmgr，无法确认当前活动启动器'
        return 1
    }
    output="$(efibootmgr -v 2>/dev/null)" || {
        KERNEL_GRUB_REASON='efibootmgr 无法读取 UEFI BootCurrent'
        return 1
    }
    current="$(awk '$1 == "BootCurrent:" {print $2; exit}' <<<"$output")"
    [[ "$current" =~ ^[[:xdigit:]]{4}$ ]] || {
        KERNEL_GRUB_REASON='UEFI BootCurrent 缺失或格式异常'
        return 1
    }
    while IFS= read -r line; do
        [[ "$line" == "Boot${current}"* ]] || continue
        active_line="$line"
        break
    done <<<"$output"
    [[ "$active_line" == *'File('*')'* ]] || {
        KERNEL_GRUB_REASON="UEFI BootCurrent ${current} 没有可验证的 EFI 文件路径"
        return 1
    }
    loader="${active_line#*File(}"
    loader="${loader%%)*}"
    loader="${loader//\\/\/}"
    lower_loader="${loader,,}"
    case "${lower_loader##*/}" in
        grub*.efi | shim*.efi) ;;
        *)
            KERNEL_GRUB_REASON="UEFI BootCurrent ${current} 并非 GRUB/shim：$loader"
            return 1
            ;;
    esac
    [[ "$loader" == /* && "$loader" != *..* ]] || {
        KERNEL_GRUB_REASON='UEFI BootCurrent 启动路径格式不安全'
        return 1
    }
    loader_path="$(vps_cmd_system_path "/boot/efi${loader}")" || return 1
    [[ -f "$loader_path" && ! -L "$loader_path" ]] || {
        KERNEL_GRUB_REASON="UEFI BootCurrent 对应的 GRUB/shim 文件不存在：/boot/efi${loader}"
        return 1
    }
}

_kernel_grub_known_release() {
    local wanted="$1" release
    [[ "$wanted" =~ ^[A-Za-z0-9][A-Za-z0-9._+~-]*$ ]] || return 1
    for release in "${KERNEL_RELEASES[@]:-}"; do
        [[ "$release" == "$wanted" ]] && return 0
    done
    return 1
}

_kernel_grub_quoted_word() {
    local value
    value="$(vps_cmd_trim "${1:-}")"
    case "${value:0:1}" in
        "'")
            value="${value:1}"
            [[ "$value" == *"'"* ]] || return 1
            printf '%s' "${value%%\'*}"
            ;;
        '"')
            value="${value:1}"
            [[ "$value" == *'"'* ]] || return 1
            printf '%s' "${value%%\"*}"
            ;;
        *) return 1 ;;
    esac
}

_kernel_grub_menu_fields() {
    local line="$1" kind="$2" remainder id_tail
    remainder="${line#*"$kind"}"
    KERNEL_GRUB_PARSED_TITLE="$(_kernel_grub_quoted_word "$remainder")" || return 1
    id_tail="${line#*\$menuentry_id_option}"
    [[ "$id_tail" != "$line" ]] || return 1
    KERNEL_GRUB_PARSED_ID="$(_kernel_grub_quoted_word "$id_tail")" || return 1
    [[ "$KERNEL_GRUB_PARSED_ID" =~ ^[A-Za-z0-9][A-Za-z0-9._+/@:=-]*$ ]] || return 1
}

_kernel_grub_assoc_unique() {
    local array_name="$1" key="$2" value="$3" existing=''
    declare -n ref="$array_name"
    if [[ -v 'ref[$key]' ]]; then
        existing="${ref["$key"]}"
        [[ "$existing" == "$value" ]] || ref["$key"]='!'
    else
        ref["$key"]="$value"
    fi
}

_kernel_grub_safe_title() {
    local title="$1"
    [[ -n "$title" && ${#title} -le 1024 ]] || return 1
    [[ "$title" != *'$'* && "$title" != *'`'* && "$title" != *$'\\'* && "$title" != *'['* && "$title" != *']'* ]]
}

_kernel_grub_title_has_exact_release() {
    local title="$1" release="$2" rest
    [[ "$title" == *"Linux ${release}"* ]] || return 1
    rest="${title#*"Linux ${release}"}"
    [[ -z "$rest" || "${rest:0:1}" == ' ' || "${rest:0:1}" == '(' ]]
}

_kernel_grub_record_entry() {
    local title="$1" id="$2" stable="$3" numeric="$4" title_path="$5" image="$6"
    local release='' submenu_id entry_id root

    [[ "${title,,}" != *recovery* && "${title,,}" != *rescue* ]] || return 0
    case "$image" in
        /boot/vmlinuz-*) release="${image#/boot/vmlinuz-}" ;;
        /vmlinuz-*) release="${image#/vmlinuz-}" ;;
        *) return 0 ;;
    esac
    _kernel_grub_known_release "$release" || return 0
    if [[ -z "$_KERNEL_GRUB_ACTIVE_ROOT" ]]; then
        case "$id" in
            gnulinux-simple-*) _KERNEL_GRUB_ACTIVE_ROOT="${id#gnulinux-simple-}" ;;
            "gnulinux-${release}-advanced-"*) _KERNEL_GRUB_ACTIVE_ROOT="${id#"gnulinux-${release}-advanced-"}" ;;
        esac
    fi
    root="$_KERNEL_GRUB_ACTIVE_ROOT"
    [[ -n "$root" ]] || return 0
    if [[ "$stable" == *'>'* ]]; then
        submenu_id="${stable%%>*}"
        entry_id="${stable#*>}"
        [[ "$submenu_id" == "gnulinux-advanced-${root}" && "$entry_id" == "gnulinux-${release}-advanced-${root}" ]] || return 0
    else
        [[ "$id" == "gnulinux-simple-${root}" || "$id" == "gnulinux-${release}-advanced-${root}" ]] || return 0
    fi
    _kernel_grub_assoc_unique _KERNEL_GRUB_RELEASE_BY_ID "$stable" "$release"
    _kernel_grub_assoc_unique _KERNEL_GRUB_RELEASE_BY_NUMBER "$numeric" "$release"
    _kernel_grub_assoc_unique _KERNEL_GRUB_ID_BY_NUMBER "$numeric" "$stable"
    if _kernel_grub_safe_title "$title_path"; then
        _kernel_grub_assoc_unique _KERNEL_GRUB_RELEASE_BY_TITLE "$title_path" "$release"
        _kernel_grub_assoc_unique _KERNEL_GRUB_ID_BY_TITLE "$title_path" "$stable"
    fi
    if _kernel_grub_title_has_exact_release "$title" "$release"; then
        _kernel_grub_assoc_unique _KERNEL_GRUB_EXACT_ENTRY "$release" "$stable"
    fi
}

_kernel_grub_parse_cfg() {
    local line trimmed image
    local submenu_id='' submenu_title='' submenu_number='' entry_id='' entry_title='' entry_image=''
    local entry_stable='' entry_number='' entry_title_path=''
    local top_index=0 child_index=0 in_entry=0 in_linux_section=0 saw_linux_section=0 entry_trusted=0

    while IFS= read -r line || [[ -n "$line" ]]; do
        trimmed="$(vps_cmd_trim "$line")"
        if [[ "$trimmed" == '### BEGIN /etc/grub.d/10_linux ###' ]]; then
            ((in_entry == 0)) || return 1
            in_linux_section=1
            saw_linux_section=1
            continue
        fi
        if [[ "$trimmed" == '### BEGIN /etc/grub.d/'*' ###' ]]; then
            ((in_entry == 0)) || return 1
            in_linux_section=0
            continue
        fi
        if [[ "$trimmed" == '### END /etc/grub.d/10_linux ###' ]]; then
            ((in_entry == 0 && ${#submenu_id} == 0)) || return 1
            in_linux_section=0
            continue
        fi
        if [[ "$trimmed" == submenu[[:space:]]* ]]; then
            ((in_entry == 0)) && [[ -z "$submenu_id" ]] || return 1
            _kernel_grub_menu_fields "$trimmed" submenu || return 1
            submenu_title="$KERNEL_GRUB_PARSED_TITLE"
            submenu_id="$KERNEL_GRUB_PARSED_ID"
            submenu_number="$top_index"
            top_index=$((top_index + 1))
            child_index=0
            continue
        fi
        if [[ "$trimmed" == menuentry[[:space:]]* ]]; then
            ((in_entry == 0)) || return 1
            _kernel_grub_menu_fields "$trimmed" menuentry || return 1
            entry_title="$KERNEL_GRUB_PARSED_TITLE"
            entry_id="$KERNEL_GRUB_PARSED_ID"
            entry_image=''
            entry_trusted="$in_linux_section"
            if [[ -n "$submenu_id" ]]; then
                entry_stable="${submenu_id}>${entry_id}"
                entry_number="${submenu_number}>${child_index}"
                entry_title_path="${submenu_title}>${entry_title}"
                child_index=$((child_index + 1))
            else
                entry_stable="$entry_id"
                entry_number="$top_index"
                entry_title_path="$entry_title"
                top_index=$((top_index + 1))
            fi
            in_entry=1
            continue
        fi
        if ((in_entry == 1)) && [[ "$trimmed" == linux[[:space:]]* || "$trimmed" == linuxefi[[:space:]]* ]]; then
            IFS=$' \t' read -r _ image _ <<<"$trimmed"
            [[ -z "$entry_image" || "$entry_image" == "$image" ]] || return 1
            entry_image="$image"
            continue
        fi
        if [[ "$trimmed" == '}' ]]; then
            if ((in_entry == 1)); then
                if ((entry_trusted == 1)); then
                    _kernel_grub_record_entry "$entry_title" "$entry_id" "$entry_stable" "$entry_number" "$entry_title_path" "$entry_image"
                fi
                in_entry=0
                entry_id=''
                continue
            fi
            if [[ -n "$submenu_id" ]]; then
                submenu_id=''
                submenu_title=''
                submenu_number=''
            fi
        fi
    done <"$KERNEL_GRUB_CFG"
    ((in_entry == 0 && ${#submenu_id} == 0 && saw_linux_section == 1))
}

_kernel_grub_parse_literal() {
    local value
    value="$(vps_cmd_trim "$1")"
    case "${value:0:1}" in
        "'")
            ((${#value} >= 2)) && [[ "${value: -1}" == "'" && "${value:1:${#value}-2}" != *"'"* ]] || return 1
            printf '%s' "${value:1:${#value}-2}"
            ;;
        '"')
            ((${#value} >= 2)) && [[ "${value: -1}" == '"' ]] || return 1
            value="${value:1:${#value}-2}"
            [[ "$value" != *'$'* && "$value" != *'`'* && "$value" != *$'\\'* ]] || return 1
            printf '%s' "$value"
            ;;
        *)
            value="${value%%[[:space:]#]*}"
            [[ "$value" =~ ^[A-Za-z0-9][A-Za-z0-9._+/@:=~\>-]*$ ]] || return 1
            printf '%s' "$value"
            ;;
    esac
}

_kernel_grub_read_default() {
    local file line rhs parsed
    local variable found=0
    local -a files=()
    KERNEL_GRUB_RAW_DEFAULT='0'
    KERNEL_GRUB_RAW_SAVEDEFAULT='false'
    [[ ! -e "$KERNEL_GRUB_DEFAULT_FILE" || (-f "$KERNEL_GRUB_DEFAULT_FILE" && ! -L "$KERNEL_GRUB_DEFAULT_FILE") ]] || return 1
    [[ ! -e "$KERNEL_GRUB_DEFAULT_FILE" ]] || files+=("$KERNEL_GRUB_DEFAULT_FILE")
    if [[ -d "$KERNEL_GRUB_DEFAULT_DIR" && ! -L "$KERNEL_GRUB_DEFAULT_DIR" ]]; then
        shopt -s nullglob
        files+=("$KERNEL_GRUB_DEFAULT_DIR"/*.cfg)
        shopt -u nullglob
    elif [[ -e "$KERNEL_GRUB_DEFAULT_DIR" ]]; then
        return 1
    fi
    for file in "${files[@]}"; do
        [[ -f "$file" && ! -L "$file" && -r "$file" ]] || return 1
        while IFS= read -r line || [[ -n "$line" ]]; do
            if [[ "$line" =~ ^[[:space:]]*(GRUB_DEFAULT|GRUB_SAVEDEFAULT)[[:space:]]*=(.*)$ ]]; then
                variable="${BASH_REMATCH[1]}"
                rhs="${BASH_REMATCH[2]}"
            else
                continue
            fi
            parsed="$(_kernel_grub_parse_literal "$rhs")" || return 1
            if [[ "$variable" == GRUB_DEFAULT ]]; then
                KERNEL_GRUB_RAW_DEFAULT="$parsed"
            else
                KERNEL_GRUB_RAW_SAVEDEFAULT="$parsed"
            fi
            found=1
        done <"$file"
    done
    : "$found"
}

_kernel_grub_cfg_default_matches() {
    local expected="$1" line trimmed rhs value
    local matched=0 invalid=0
    [[ "$expected" != saved ]] || expected='${saved_entry}'
    while IFS= read -r line || [[ -n "$line" ]]; do
        trimmed="$(vps_cmd_trim "$line")"
        [[ "$trimmed" == 'set default='* ]] || continue
        rhs="${trimmed#set default=}"
        case "${rhs:0:1}" in
            '"')
                [[ "${rhs: -1}" == '"' ]] || continue
                value="${rhs:1:${#rhs}-2}"
                ;;
            "'")
                [[ "${rhs: -1}" == "'" ]] || continue
                value="${rhs:1:${#rhs}-2}"
                ;;
            *) value="$rhs" ;;
        esac
        [[ "$value" == '${next_entry}' ]] && continue
        if [[ "$value" == "$expected" ]]; then
            matched=1
        else
            invalid=1
        fi
    done <"$KERNEL_GRUB_CFG"
    ((matched == 1 && invalid == 0))
}

_kernel_grub_read_env_value() {
    local wanted="$1" line key value found=''
    [[ ! -e "$KERNEL_GRUB_ENV" ]] && return 1
    [[ -f "$KERNEL_GRUB_ENV" && ! -L "$KERNEL_GRUB_ENV" && -r "$KERNEL_GRUB_ENV" ]] || return 2
    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ "$line" == '# GRUB Environment Block' || "$line" == '#'* ]] && continue
        [[ "$line" == *=* ]] || continue
        key="${line%%=*}"
        value="${line#*=}"
        [[ "$key" == "$wanted" ]] || continue
        [[ "$value" != *[$'\001'-$'\037']* && ${#value} -le 4096 ]] || return 2
        found="$value"
    done <"$KERNEL_GRUB_ENV"
    [[ -n "$found" ]] || return 1
    printf '%s' "$found"
}

_kernel_grub_resolve_selector() {
    local selector="$1" key release='' stable=''
    for key in "${!_KERNEL_GRUB_RELEASE_BY_ID[@]}"; do
        [[ "$key" == "$selector" ]] || continue
        release="${_KERNEL_GRUB_RELEASE_BY_ID["$key"]}"
        stable="$key"
        break
    done
    if [[ -z "$release" && "$selector" =~ ^[0-9]+(\>[0-9]+)?$ ]]; then
        for key in "${!_KERNEL_GRUB_RELEASE_BY_NUMBER[@]}"; do
            [[ "$key" == "$selector" ]] || continue
            release="${_KERNEL_GRUB_RELEASE_BY_NUMBER["$key"]}"
            stable="${_KERNEL_GRUB_ID_BY_NUMBER["$key"]}"
            break
        done
    fi
    if [[ -z "$release" ]]; then
        for key in "${!_KERNEL_GRUB_RELEASE_BY_TITLE[@]}"; do
            [[ "$key" == "$selector" ]] || continue
            release="${_KERNEL_GRUB_RELEASE_BY_TITLE["$key"]}"
            stable="${_KERNEL_GRUB_ID_BY_TITLE["$key"]}"
            break
        done
    fi
    [[ -n "$release" && "$release" != '!' && -n "$stable" && "$stable" != '!' ]] || return 1
    KERNEL_GRUB_RESOLVED_RELEASE="$release"
    KERNEL_GRUB_RESOLVED_ID="$stable"
}

kernel_grub_load() {
    local release saved='' next='' selector env_status=0
    KERNEL_GRUB_SUPPORTED=0
    KERNEL_GRUB_REASON='GRUB2 状态未知'
    KERNEL_GRUB_DEFAULT_RELEASE=''
    KERNEL_GRUB_NEXT_RELEASE=''
    KERNEL_GRUB_DEFAULT_ID=''
    KERNEL_GRUB_NEXT_ID=''
    KERNEL_GRUB_DEFAULT_SELECTOR=''
    KERNEL_GRUB_NEXT_SELECTOR=''
    KERNEL_GRUB_ENTRY=()
    _KERNEL_GRUB_RELEASE_BY_ID=()
    _KERNEL_GRUB_RELEASE_BY_NUMBER=()
    _KERNEL_GRUB_RELEASE_BY_TITLE=()
    _KERNEL_GRUB_EXACT_ENTRY=()
    _KERNEL_GRUB_ID_BY_NUMBER=()
    _KERNEL_GRUB_ID_BY_TITLE=()
    _KERNEL_GRUB_ACTIVE_ROOT=''

    kernel_grub_probe_active || return 0
    _kernel_grub_parse_cfg || {
        KERNEL_GRUB_REASON='grub.cfg 菜单结构异常或缺少稳定 menuentry ID'
        return 0
    }
    for release in "${KERNEL_RELEASES[@]:-}"; do
        [[ -v '_KERNEL_GRUB_EXACT_ENTRY[$release]' ]] || continue
        [[ "${_KERNEL_GRUB_EXACT_ENTRY["$release"]}" != '!' ]] || continue
        KERNEL_GRUB_ENTRY["$release"]="${_KERNEL_GRUB_EXACT_ENTRY["$release"]}"
    done
    _kernel_grub_read_default || {
        KERNEL_GRUB_REASON='无法安全解析 GRUB_DEFAULT（只接受不含展开的字面量）'
        return 0
    }
    _kernel_grub_cfg_default_matches "$KERNEL_GRUB_RAW_DEFAULT" || {
        KERNEL_GRUB_REASON='grub.cfg 中的有效 default 与安全读取的 GRUB_DEFAULT 不一致'
        return 0
    }
    selector="$KERNEL_GRUB_RAW_DEFAULT"
    if [[ "$selector" == saved ]]; then
        saved="$(_kernel_grub_read_env_value saved_entry)" || env_status=$?
        if ((env_status != 0)); then
            KERNEL_GRUB_REASON='GRUB_DEFAULT=saved，但 grubenv 中没有可解析的 saved_entry'
            return 0
        fi
        selector="$saved"
    fi
    KERNEL_GRUB_DEFAULT_SELECTOR="$selector"
    if ! _kernel_grub_resolve_selector "$selector"; then
        KERNEL_GRUB_REASON="GRUB 默认项无法唯一关联到已知完整内核：$selector"
        return 0
    fi
    KERNEL_GRUB_DEFAULT_RELEASE="$KERNEL_GRUB_RESOLVED_RELEASE"
    KERNEL_GRUB_DEFAULT_ID="$KERNEL_GRUB_RESOLVED_ID"
    env_status=0
    next="$(_kernel_grub_read_env_value next_entry)" || env_status=$?
    case "$env_status" in
        0)
            KERNEL_GRUB_NEXT_SELECTOR="$next"
            if ! _kernel_grub_resolve_selector "$next"; then
                KERNEL_GRUB_REASON="grubenv next_entry 无法唯一关联到已知完整内核：$next"
                return 0
            fi
            KERNEL_GRUB_NEXT_RELEASE="$KERNEL_GRUB_RESOLVED_RELEASE"
            KERNEL_GRUB_NEXT_ID="$KERNEL_GRUB_RESOLVED_ID"
            ;;
        1) ;;
        *)
            KERNEL_GRUB_REASON='grubenv 不是可安全读取的普通环境块'
            return 0
            ;;
    esac
    KERNEL_GRUB_SUPPORTED=1
    KERNEL_GRUB_REASON='已确认发行版 GRUB2、活动启动路径和可解析默认项'
}

kernel_grub_require() {
    [[ "$KERNEL_GRUB_SUPPORTED" == 1 ]] || {
        vps_cmd_error "GRUB2 内核切换不可用：${KERNEL_GRUB_REASON:-未知原因}"
        return 3
    }
    [[ -n "$KERNEL_GRUB_DEFAULT_RELEASE" ]] || {
        vps_cmd_error 'GRUB2 当前默认项无法解析，拒绝修改'
        return 3
    }
    [[ -z "$KERNEL_GRUB_NEXT_ID" || -n "$KERNEL_GRUB_NEXT_RELEASE" ]] || {
        vps_cmd_error 'GRUB2 一次性 next_entry 无法解析，拒绝修改'
        return 3
    }
}

_kernel_grub_restore() {
    local backup="$1" failed=0
    if [[ -f "$backup/dropin" ]]; then
        cp -p -- "$backup/dropin" "$KERNEL_GRUB_DROPIN" || failed=1
    else
        rm -f -- "$KERNEL_GRUB_DROPIN" || failed=1
    fi
    update-grub >/dev/null 2>&1 || failed=1
    if [[ -f "$backup/grub.cfg" ]]; then
        cp -p -- "$backup/grub.cfg" "$KERNEL_GRUB_CFG" || failed=1
    fi
    if [[ -f "$backup/grubenv" ]]; then
        cp -p -- "$backup/grubenv" "$KERNEL_GRUB_ENV" || failed=1
    else
        rm -f -- "$KERNEL_GRUB_ENV" || failed=1
    fi
    if [[ -f "$backup/dropin" ]]; then
        cmp -s -- "$backup/dropin" "$KERNEL_GRUB_DROPIN" || failed=1
    else
        [[ ! -e "$KERNEL_GRUB_DROPIN" ]] || failed=1
    fi
    [[ ! -f "$backup/grub.cfg" ]] || cmp -s -- "$backup/grub.cfg" "$KERNEL_GRUB_CFG" || failed=1
    if [[ -f "$backup/grubenv" ]]; then
        cmp -s -- "$backup/grubenv" "$KERNEL_GRUB_ENV" || failed=1
    else
        [[ ! -e "$KERNEL_GRUB_ENV" ]] || failed=1
    fi
    ((failed == 0))
}

_kernel_grub_transaction_exit() {
    local status="$1"
    trap - EXIT HUP INT TERM
    if [[ "${_KERNEL_GRUB_TX_ACTIVE:-0}" == 1 ]]; then
        vps_cmd_warning 'GRUB 事务未完成，正在恢复原配置'
        if _kernel_grub_restore "$_KERNEL_GRUB_TX_BACKUP"; then
            vps_cmd_warning "已恢复原配置；故障现场与备份保留在 $_KERNEL_GRUB_TX_BACKUP"
        else
            vps_cmd_error "自动恢复验证失败；请从 $_KERNEL_GRUB_TX_BACKUP 手工恢复 dropin、grub.cfg 和 grubenv"
            status=30
        fi
    fi
    exit "$status"
}

_kernel_grub_transaction_signal() {
    local status="$1"
    vps_cmd_error '收到中断信号，GRUB 事务将回滚'
    exit "$status"
}

_kernel_grub_apply_transaction() (
    local release="$1" target="$2" backup
    _KERNEL_GRUB_TX_ACTIVE=0
    _KERNEL_GRUB_TX_BACKUP=''
    trap '_kernel_grub_transaction_exit $?' EXIT
    trap '_kernel_grub_transaction_signal 129' HUP
    trap '_kernel_grub_transaction_signal 130' INT
    trap '_kernel_grub_transaction_signal 143' TERM

    install -d -m 0755 -- "$KERNEL_GRUB_DEFAULT_DIR" "${KERNEL_GRUB_BACKUP_ROOT%/backups}" || return 20
    install -d -m 0700 -- "$KERNEL_GRUB_BACKUP_ROOT" || return 20
    backup="$(mktemp -d "${KERNEL_GRUB_BACKUP_ROOT}/$(date -u +%Y%m%dT%H%M%SZ).XXXXXX")" || return 20
    chmod 0700 -- "$backup" || return 20
    cp -p -- "$KERNEL_GRUB_CFG" "$backup/grub.cfg" || return 20
    [[ ! -e "$KERNEL_GRUB_ENV" ]] || cp -p -- "$KERNEL_GRUB_ENV" "$backup/grubenv" || return 20
    [[ ! -e "$KERNEL_GRUB_DROPIN" ]] || cp -p -- "$KERNEL_GRUB_DROPIN" "$backup/dropin" || return 20
    _KERNEL_GRUB_TX_BACKUP="$backup"
    _KERNEL_GRUB_TX_ACTIVE=1

    {
        printf '%s\n' "$KERNEL_MANAGED_MARKER"
        printf "GRUB_DEFAULT='%s'\n" "$target"
        printf 'GRUB_SAVEDEFAULT=false\n'
    } | vps_cmd_atomic_write /etc/default/grub.d/99-vpsctl-kernel.cfg 0644 || {
        vps_cmd_error '写入受管 GRUB 配置失败'
        return 20
    }
    grub-editenv "$KERNEL_GRUB_ENV" unset next_entry || {
        vps_cmd_error '清除遗留 next_entry 失败'
        return 20
    }
    update-grub || {
        vps_cmd_error 'update-grub 失败'
        return 20
    }

    kernel_grub_load
    if [[ "$KERNEL_GRUB_SUPPORTED" != 1 || "$KERNEL_GRUB_DEFAULT_RELEASE" != "$release" || -n "$KERNEL_GRUB_NEXT_ID" ]]; then
        vps_cmd_error 'GRUB 更新后回读验证失败'
        return 20
    fi
    _KERNEL_GRUB_TX_ACTIVE=0
    vps_cmd_success "已将下次及后续启动永久固定为内核 $release；未自动重启"
    vps_cmd_info "恢复备份保留在 $backup"
    return 0
)

kernel_grub_switch() {
    local release="${1:-}" target candidate
    local complete=0 managed=0

    [[ "$release" =~ ^[A-Za-z0-9][A-Za-z0-9._+~-]*$ ]] || {
        vps_cmd_error '内核版本格式不安全'
        return 2
    }
    kernel_inventory_load || return $?
    _kernel_grub_known_release "$release" || {
        vps_cmd_error "未安装内核版本：$release"
        return 3
    }
    complete="${KERNEL_RELEASE_COMPLETE["$release"]:-0}"
    [[ "$complete" == 1 ]] || {
        vps_cmd_error "内核 $release 的启动文件或模块不完整，拒绝设为默认"
        return 3
    }
    managed="${KERNEL_RELEASE_MANAGED["$release"]:-0}"
    [[ "$managed" == 1 ]] || {
        vps_cmd_error "内核 $release 不属于可验证的软件包库存，拒绝设为默认"
        return 3
    }
    kernel_grub_load
    kernel_grub_require || return $?
    target="${KERNEL_GRUB_ENTRY["$release"]:-}"
    [[ -n "$target" && "$target" =~ ^[A-Za-z0-9][A-Za-z0-9._+/@:=-]*(\>[A-Za-z0-9][A-Za-z0-9._+/@:=-]*)?$ ]] || {
        vps_cmd_error "GRUB 菜单没有 $release 的唯一精确稳定 ID 项"
        return 3
    }
    for candidate in "$KERNEL_GRUB_CFG" "$KERNEL_GRUB_ENV" "$KERNEL_GRUB_DROPIN" "$KERNEL_GRUB_BACKUP_ROOT"; do
        vps_cmd_require_no_symlink_components "$candidate" || return $?
    done
    if [[ -e "$KERNEL_GRUB_DROPIN" ]]; then
        [[ -f "$KERNEL_GRUB_DROPIN" && ! -L "$KERNEL_GRUB_DROPIN" ]] || {
            vps_cmd_error '/etc/default/grub.d/99-vpsctl-kernel.cfg 不是普通文件，拒绝覆盖'
            return 10
        }
        grep -Fqx "$KERNEL_MANAGED_MARKER" "$KERNEL_GRUB_DROPIN" || {
            vps_cmd_error '/etc/default/grub.d/99-vpsctl-kernel.cfg 已存在但不属于 vpsctl，拒绝覆盖'
            return 10
        }
    fi
    if [[ "${VPSCTL_DRY_RUN:-0}" == 1 ]]; then
        vps_cmd_info "演练：将永久固定 GRUB_DEFAULT=$target（内核 $release）"
        vps_cmd_info '演练：将设置 GRUB_SAVEDEFAULT=false、运行 update-grub，并清除 grubenv next_entry'
        return 0
    fi

    _kernel_grub_apply_transaction "$release" "$target"
}
