#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2016,SC2034,SC2317

set -Eeuo pipefail
IFS=$'\n\t'

TEST_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd -P)"
readonly TEST_ROOT
TEST_TEMP='/tmp/vpsctl-kernel-grub-20260905'
TEST_SYSTEM_ROOT="${TEST_TEMP}/system"
readonly TEST_TEMP TEST_SYSTEM_ROOT
[[ "$TEST_TEMP" == /tmp/vpsctl-kernel-grub-20260905 ]] || exit 1
rm -rf -- "$TEST_TEMP"
mkdir -p "$TEST_SYSTEM_ROOT"
trap 'rm -rf -- "$TEST_TEMP"' EXIT

export VPSCTL_TESTING=1 VPSCTL_SYSTEM_ROOT="$TEST_SYSTEM_ROOT"
export VPSCTL_NON_INTERACTIVE=1 VPSCTL_NO_COLOR=1 VPSCTL_DRY_RUN=0

# shellcheck source=../../lib/command.sh
source "$TEST_ROOT/lib/command.sh"
readonly KERNEL_MANAGED_MARKER='# Managed by vpsctl system kernel.'
# shellcheck source=../../commands/system/kernel/grub.sh
source "$TEST_ROOT/commands/system/kernel/grub.sh"

if [[ "${1:-}" == --real-readonly ]]; then
    VPSCTL_TESTING=0
    unset VPSCTL_SYSTEM_ROOT
    vps_cmd_init system-kernel-grub-readonly "$TEST_ROOT"
    kernel_grub_init_paths
    KERNEL_RELEASES=()
    declare -A KERNEL_RELEASE_COMPLETE=() KERNEL_RELEASE_MANAGED=() KERNEL_RELEASE_PACKAGES=()
    shopt -s nullglob
    for image in /boot/vmlinuz-*; do
        release="${image##*/vmlinuz-}"
        KERNEL_RELEASES+=("$release")
        KERNEL_RELEASE_COMPLETE["$release"]=1
    done
    shopt -u nullglob
    kernel_grub_load
    printf 'supported=%s\nreason=%s\ndefault_release=%s\ndefault_selector=%s\ndefault_id=%s\nentries=%s\n' \
        "$KERNEL_GRUB_SUPPORTED" "$KERNEL_GRUB_REASON" "$KERNEL_GRUB_DEFAULT_RELEASE" \
        "$KERNEL_GRUB_DEFAULT_SELECTOR" "$KERNEL_GRUB_DEFAULT_ID" "${#KERNEL_GRUB_ENTRY[@]}"
    [[ "$KERNEL_GRUB_SUPPORTED" == 1 && -n "$KERNEL_GRUB_DEFAULT_RELEASE" && ${#KERNEL_GRUB_ENTRY[@]} -gt 0 ]]
    exit
fi

KERNEL_RELEASES=(
    7.1.11-x64v3-xanmod1
    6.12.12-amd64
    6.12.9-amd64
)
declare -A KERNEL_RELEASE_COMPLETE=(
    ["7.1.11-x64v3-xanmod1"]=1
    ["6.12.12-amd64"]=1
    ["6.12.9-amd64"]=1
)
declare -A KERNEL_RELEASE_MANAGED=(
    ["7.1.11-x64v3-xanmod1"]=1
    ["6.12.12-amd64"]=1
    ["6.12.9-amd64"]=1
)
declare -A KERNEL_RELEASE_PACKAGES=()

test_fail() {
    printf 'FAIL: %s\n' "$1" >&2
    exit 1
}

assert_equal() {
    [[ "$1" == "$2" ]] || test_fail "$3: expected '$1', got '$2'"
}

assert_contains() {
    [[ "$1" == *"$2"* ]] || test_fail "$3: missing '$2' in '$1'"
}

assert_status() {
    local expected="$1" message="$2" status=0
    shift 2
    "$@" >/dev/null 2>&1 || status=$?
    assert_equal "$expected" "$status" "$message"
}

kernel_inventory_load() { return 0; }
kernel_grub_probe_active() { return 0; }

write_grub_cfg() {
    local default_value="$1"
    mkdir -p "$TEST_SYSTEM_ROOT/boot/grub"
    cat >"$KERNEL_GRUB_CFG" <<EOF
# DO NOT EDIT THIS FILE
# generated by grub-mkconfig
set default="$default_value"
### BEGIN /etc/grub.d/10_linux ###
menuentry 'Debian GNU/Linux' --class debian \$menuentry_id_option 'gnulinux-simple-UUID' {
    linux /boot/vmlinuz-7.1.11-x64v3-xanmod1 root=UUID=root-a ro
}
submenu 'Advanced options for Debian GNU/Linux' \$menuentry_id_option 'gnulinux-advanced-UUID' {
    menuentry 'Debian GNU/Linux, with Linux 6.12.12-amd64' \$menuentry_id_option 'gnulinux-6.12.12-amd64-advanced-UUID' {
        linux /boot/vmlinuz-6.12.12-amd64 root=UUID=root-a ro
    }
    menuentry 'Debian GNU/Linux, with Linux 6.12.12-amd64 (recovery mode)' \$menuentry_id_option 'gnulinux-6.12.12-amd64-recovery-UUID' {
        linux /boot/vmlinuz-6.12.12-amd64 root=UUID=root-a ro single
    }
    menuentry 'Debian GNU/Linux, with Linux 6.12.9-amd64' \$menuentry_id_option 'gnulinux-6.12.9-amd64-advanced-UUID' {
        linux /boot/vmlinuz-6.12.9-amd64 root=UUID=root-a ro
    }
    menuentry 'Debian GNU/Linux, with Linux 7.1.11-x64v3-xanmod1' \$menuentry_id_option 'gnulinux-7.1.11-x64v3-xanmod1-advanced-UUID' {
        linux /boot/vmlinuz-7.1.11-x64v3-xanmod1 root=UUID=root-a ro
    }
}
### END /etc/grub.d/10_linux ###
EOF
}

write_defaults() {
    local value="$1"
    mkdir -p "$TEST_SYSTEM_ROOT/etc/default/grub.d"
    printf "GRUB_DEFAULT='%s'\nGRUB_SAVEDEFAULT=false\n" "$value" >"$KERNEL_GRUB_DEFAULT_FILE"
}

write_env() {
    mkdir -p "${KERNEL_GRUB_ENV%/*}"
    {
        printf '# GRUB Environment Block\n'
        printf '%s\n' "$@"
        printf '########################################\n'
    } >"$KERNEL_GRUB_ENV"
}

reset_fixture() {
    rm -rf -- "$TEST_SYSTEM_ROOT"
    mkdir -p \
        "$TEST_SYSTEM_ROOT/etc/default/grub.d" \
        "$TEST_SYSTEM_ROOT/boot/grub" \
        "$TEST_SYSTEM_ROOT/var/lib/vpsctl/system/kernel"
    vps_cmd_init system-kernel-grub "$TEST_ROOT"
    kernel_grub_init_paths
    write_defaults 0
    write_grub_cfg 0
    write_env
    VPSCTL_DRY_RUN=0
    KERNEL_RELEASE_COMPLETE["6.12.12-amd64"]=1
}

test_load_selectors_and_exact_entries() {
    local title stable
    reset_fixture
    kernel_grub_load
    assert_equal 1 "$KERNEL_GRUB_SUPPORTED" 'standard generated GRUB support'
    assert_equal 7.1.11-x64v3-xanmod1 "$KERNEL_GRUB_DEFAULT_RELEASE" 'numeric zero release'
    assert_equal 0 "$KERNEL_GRUB_DEFAULT_SELECTOR" 'numeric selector exposure'
    assert_equal gnulinux-simple-UUID "$KERNEL_GRUB_DEFAULT_ID" 'numeric selector stable ID'
    stable='gnulinux-advanced-UUID>gnulinux-6.12.12-amd64-advanced-UUID'
    assert_equal "$stable" "${KERNEL_GRUB_ENTRY["6.12.12-amd64"]}" 'exact submenu stable ID'

    write_defaults '1>2'
    write_grub_cfg '1>2'
    kernel_grub_load
    assert_equal 6.12.9-amd64 "$KERNEL_GRUB_DEFAULT_RELEASE" 'numeric submenu path'
    assert_equal '1>2' "$KERNEL_GRUB_DEFAULT_SELECTOR" 'numeric submenu selector exposure'

    title='Advanced options for Debian GNU/Linux>Debian GNU/Linux, with Linux 6.12.12-amd64'
    write_defaults "$title"
    write_grub_cfg "$title"
    kernel_grub_load
    assert_equal 6.12.12-amd64 "$KERNEL_GRUB_DEFAULT_RELEASE" 'title submenu path'
    assert_equal "$stable" "$KERNEL_GRUB_DEFAULT_ID" 'title selector stable ID'

    write_defaults saved
    write_grub_cfg '${saved_entry}'
    write_env "saved_entry=$stable" 'next_entry=1>2'
    kernel_grub_load
    assert_equal 1 "$KERNEL_GRUB_SUPPORTED" 'saved and next parsing'
    assert_equal "$stable" "$KERNEL_GRUB_DEFAULT_SELECTOR" 'expanded saved selector'
    assert_equal 6.12.12-amd64 "$KERNEL_GRUB_DEFAULT_RELEASE" 'saved release'
    assert_equal '1>2' "$KERNEL_GRUB_NEXT_SELECTOR" 'next selector exposure'
    assert_equal 6.12.9-amd64 "$KERNEL_GRUB_NEXT_RELEASE" 'next release'
    assert_equal 'gnulinux-advanced-UUID>gnulinux-6.12.9-amd64-advanced-UUID' "$KERNEL_GRUB_NEXT_ID" 'next stable ID'
}

test_single_level_and_other_section_counting() {
    local stable='gnulinux-6.12.12-amd64-advanced-UUID'
    reset_fixture
    write_defaults 2
    cat >"$KERNEL_GRUB_CFG" <<'EOF'
# DO NOT EDIT THIS FILE
# generated by grub-mkconfig
set default="2"
### BEGIN /etc/grub.d/09_foreign ###
menuentry 'Foreign Linux 6.12.12-amd64' $menuentry_id_option 'custom-foreign' {
    linux /boot/vmlinuz-6.12.12-amd64 root=UUID=root-b ro
}
### END /etc/grub.d/09_foreign ###
### BEGIN /etc/grub.d/10_linux ###
menuentry 'Debian GNU/Linux' $menuentry_id_option 'gnulinux-simple-UUID' {
    linux /boot/vmlinuz-7.1.11-x64v3-xanmod1 root=UUID=root-a ro
}
menuentry 'Debian GNU/Linux, with Linux 6.12.12-amd64' $menuentry_id_option 'gnulinux-6.12.12-amd64-advanced-UUID' {
    linux /boot/vmlinuz-6.12.12-amd64 root=UUID=root-a ro
}
### END /etc/grub.d/10_linux ###
EOF
    kernel_grub_load
    assert_equal 1 "$KERNEL_GRUB_SUPPORTED" 'single-level generated menu support'
    assert_equal 6.12.12-amd64 "$KERNEL_GRUB_DEFAULT_RELEASE" 'other section counted in numeric selector'
    assert_equal "$stable" "$KERNEL_GRUB_DEFAULT_ID" 'single-level stable ID'
    assert_equal "$stable" "${KERNEL_GRUB_ENTRY["6.12.12-amd64"]}" 'single-level exact switch entry'
}

test_efi_bootcurrent_probe() {
    reset_fixture
    mkdir -p "$TEST_SYSTEM_ROOT/sys/firmware/efi" "$TEST_SYSTEM_ROOT/boot/efi/EFI/debian"
    printf 'efi\n' >"$TEST_SYSTEM_ROOT/boot/efi/EFI/debian/shimx64.efi"
    efibootmgr() {
        printf 'BootCurrent: 0001\nBoot0001* Linux Boot Manager HD(1,GPT,...)/File(\\EFI\\systemd\\systemd-bootx64.efi)\n'
    }
    assert_status 1 'systemd-boot BootCurrent rejected' _kernel_grub_probe_efi_bootcurrent
    assert_contains "$KERNEL_GRUB_REASON" '并非 GRUB/shim' 'non-GRUB BootCurrent diagnostic'
    efibootmgr() {
        printf 'BootCurrent: 0003\nBoot0003* debian HD(1,GPT,...)/File(\\EFI\\debian\\shimx64.efi)\n'
    }
    _kernel_grub_probe_efi_bootcurrent || test_fail 'active shim BootCurrent was rejected'
}

test_fail_closed_parsing() {
    local marker="$TEST_TEMP/injected" foreign
    reset_fixture
    printf 'GRUB_DEFAULT="$(touch %s)"\n' "$marker" >"$KERNEL_GRUB_DEFAULT_FILE"
    kernel_grub_load
    assert_equal 0 "$KERNEL_GRUB_SUPPORTED" 'command substitution rejected'
    [[ ! -e "$marker" ]] || test_fail 'configuration text was executed'
    assert_contains "$KERNEL_GRUB_REASON" '安全解析' 'unsafe config diagnostic'

    reset_fixture
    write_defaults '1>0'
    write_grub_cfg 0
    kernel_grub_load
    assert_equal 0 "$KERNEL_GRUB_SUPPORTED" 'generated/config mismatch rejected'
    assert_contains "$KERNEL_GRUB_REASON" '不一致' 'generated/config mismatch diagnostic'

    reset_fixture
    foreign='gnulinux-6.12.12-amd64-advanced-OTHER-ROOT'
    write_defaults "$foreign"
    write_grub_cfg "$foreign"
    sed -i '/### END \/etc\/grub.d\/10_linux ###/i\
menuentry '\''Debian GNU/Linux, with Linux 6.12.12-amd64'\'' $menuentry_id_option '\''gnulinux-6.12.12-amd64-advanced-OTHER-ROOT'\'' {\
    linux /boot/vmlinuz-6.12.12-amd64 root=UUID=root-b ro\
}' "$KERNEL_GRUB_CFG"
    kernel_grub_load
    assert_equal 0 "$KERNEL_GRUB_SUPPORTED" 'cross-root stable ID rejected'
    assert_contains "$KERNEL_GRUB_REASON" '无法唯一关联' 'cross-root diagnostic'

    reset_fixture
    sed -i '/submenu '\''Advanced options/a\
    submenu '\''Nested options'\'' $menuentry_id_option '\''gnulinux-nested-UUID'\'' {' "$KERNEL_GRUB_CFG"
    kernel_grub_load
    assert_equal 0 "$KERNEL_GRUB_SUPPORTED" 'nested submenu rejected'
    assert_contains "$KERNEL_GRUB_REASON" '菜单结构异常' 'nested submenu diagnostic'

    reset_fixture
    write_env 'next_entry=missing-entry'
    kernel_grub_load
    assert_equal 0 "$KERNEL_GRUB_SUPPORTED" 'unknown next entry rejected'
    assert_status 3 'require rejects unknown next entry' kernel_grub_require

    reset_fixture
    kernel_grub_probe_active() {
        KERNEL_GRUB_REASON='fixture inactive boot path'
        return 1
    }
    kernel_grub_load
    assert_equal 0 "$KERNEL_GRUB_SUPPORTED" 'inactive GRUB probe'
    assert_equal 'fixture inactive boot path' "$KERNEL_GRUB_REASON" 'probe diagnostic retained'
    kernel_grub_probe_active() { return 0; }
}

test_dry_run_and_gates() {
    local before_cfg before_env output status=0
    reset_fixture
    before_cfg="$(sha256sum "$KERNEL_GRUB_CFG")"
    before_env="$(sha256sum "$KERNEL_GRUB_ENV")"
    VPSCTL_DRY_RUN=1
    output="$(kernel_grub_switch 6.12.12-amd64 2>&1)" || status=$?
    assert_equal 0 "$status" 'dry-run switch'
    assert_contains "$output" '永久固定' 'dry-run persistent plan'
    assert_equal "$before_cfg" "$(sha256sum "$KERNEL_GRUB_CFG")" 'dry-run grub.cfg unchanged'
    assert_equal "$before_env" "$(sha256sum "$KERNEL_GRUB_ENV")" 'dry-run grubenv unchanged'
    [[ ! -e "$KERNEL_GRUB_DROPIN" && ! -e "$KERNEL_GRUB_BACKUP_ROOT" ]] || test_fail 'dry-run created managed state'

    VPSCTL_DRY_RUN=0
    KERNEL_RELEASE_COMPLETE["6.12.12-amd64"]=0
    assert_status 3 'incomplete kernel gate' kernel_grub_switch 6.12.12-amd64
    KERNEL_RELEASE_COMPLETE["6.12.12-amd64"]=1
    KERNEL_RELEASE_MANAGED["6.12.12-amd64"]=0
    assert_status 3 'unmanaged inventory kernel gate' kernel_grub_switch 6.12.12-amd64
    KERNEL_RELEASE_MANAGED["6.12.12-amd64"]=1
    printf 'foreign\n' >"$KERNEL_GRUB_DROPIN"
    assert_status 10 'foreign drop-in conflict' kernel_grub_switch 6.12.12-amd64
}

update_grub_fixture() {
    local selected=0 line
    if [[ -f "$KERNEL_GRUB_DROPIN" ]]; then
        while IFS= read -r line; do
            [[ "$line" == GRUB_DEFAULT=* ]] || continue
            selected="${line#GRUB_DEFAULT=}"
            selected="${selected#\'}"
            selected="${selected%\'}"
        done <"$KERNEL_GRUB_DROPIN"
    fi
    sed -i "s|^set default=.*|set default=\"${selected}\"|" "$KERNEL_GRUB_CFG"
}

grub_editenv_fixture() {
    local file="$1" operation="$2" key="$3" temporary
    [[ "$operation" == unset && "$key" == next_entry ]] || return 1
    temporary="${file}.new"
    awk -F= '$1 != "next_entry" {print}' "$file" >"$temporary"
    mv -- "$temporary" "$file"
}

test_switch_success() {
    local output status=0 stable order="$TEST_TEMP/action-order"
    reset_fixture
    stable='gnulinux-advanced-UUID>gnulinux-6.12.12-amd64-advanced-UUID'
    write_env 'next_entry=1>2'
    update-grub() {
        printf 'update\n' >>"$order"
        update_grub_fixture
    }
    grub-editenv() {
        printf 'unset\n' >>"$order"
        grub_editenv_fixture "$@"
    }
    output="$(kernel_grub_switch 6.12.12-amd64 2>&1)" || status=$?
    assert_equal 0 "$status" 'persistent switch'
    grep -Fqx "$KERNEL_MANAGED_MARKER" "$KERNEL_GRUB_DROPIN" || test_fail 'managed marker missing'
    grep -Fqx "GRUB_DEFAULT='$stable'" "$KERNEL_GRUB_DROPIN" || test_fail 'stable default missing'
    grep -Fqx 'GRUB_SAVEDEFAULT=false' "$KERNEL_GRUB_DROPIN" || test_fail 'savedefault was not disabled'
    ! grep -q '^next_entry=' "$KERNEL_GRUB_ENV" || test_fail 'next_entry was not cleared'
    assert_equal $'unset\nupdate' "$(<"$order")" 'next_entry cleared before GRUB generation'
    assert_contains "$output" '未自动重启' 'no automatic reboot message'
    [[ -d "$KERNEL_GRUB_BACKUP_ROOT" ]] || test_fail 'backup root missing'
    [[ "$(find "$KERNEL_GRUB_BACKUP_ROOT" -mindepth 1 -maxdepth 1 -type d | wc -l)" == 1 ]] || test_fail 'unique backup missing'
}

test_transaction_rollback() {
    local old_cfg old_env status=0 counter="$TEST_TEMP/update-count"
    reset_fixture
    write_env 'saved_entry=gnulinux-simple-UUID' 'next_entry=1>2'
    old_cfg="$(sha256sum "$KERNEL_GRUB_CFG")"
    old_env="$(sha256sum "$KERNEL_GRUB_ENV")"
    update-grub() {
        local count=0
        [[ ! -f "$counter" ]] || read -r count <"$counter"
        count=$((count + 1))
        printf '%s\n' "$count" >"$counter"
        ((count > 1)) || return 1
        update_grub_fixture
    }
    grub-editenv() { grub_editenv_fixture "$@"; }
    kernel_grub_switch 6.12.12-amd64 >/dev/null 2>&1 || status=$?
    assert_equal 20 "$status" 'failed update with verified rollback'
    [[ ! -e "$KERNEL_GRUB_DROPIN" ]] || test_fail 'rollback left newly-created drop-in'
    assert_equal "$old_cfg" "$(sha256sum "$KERNEL_GRUB_CFG")" 'rollback grub.cfg'
    assert_equal "$old_env" "$(sha256sum "$KERNEL_GRUB_ENV")" 'rollback grubenv'
    grep -Fqx 'next_entry=1>2' "$KERNEL_GRUB_ENV" || test_fail 'rollback did not restore old next_entry'
    [[ "$(<"$counter")" == 2 ]] || test_fail 'rollback did not regenerate GRUB'

    reset_fixture
    old_cfg="$(sha256sum "$KERNEL_GRUB_CFG")"
    update-grub() { return 1; }
    status=0
    kernel_grub_switch 6.12.12-amd64 >/dev/null 2>&1 || status=$?
    assert_equal 30 "$status" 'rollback regeneration failure is critical'
    assert_equal "$old_cfg" "$(sha256sum "$KERNEL_GRUB_CFG")" 'critical rollback still restores generated file bytes'
}

reset_fixture
printf 'TEST: GRUB selector parsing and stable entry mapping\n'
test_load_selectors_and_exact_entries
printf 'TEST: GRUB single-level menu and section counting\n'
test_single_level_and_other_section_counting
printf 'TEST: GRUB UEFI BootCurrent proof\n'
test_efi_bootcurrent_probe
printf 'TEST: GRUB parser fail-closed behavior\n'
test_fail_closed_parsing
printf 'TEST: GRUB dry-run and mutation gates\n'
test_dry_run_and_gates
printf 'TEST: GRUB persistent switch transaction\n'
test_switch_success
printf 'TEST: GRUB rollback transaction\n'
test_transaction_rollback
printf 'PASS: system kernel GRUB tests\n'
