#!/usr/bin/env bash
# Exercise BIOS GRUB planning with real parsers and isolated command fixtures.
# No unit fixture may install packages or write a host block device.
# shellcheck disable=SC1091,SC2016,SC2030,SC2031,SC2034,SC2317
# shellcheck source-path=SCRIPTDIR

set -Eeuo pipefail
IFS=$'\n\t'

TEST_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd -P)"
readonly TEST_ROOT
TEST_TEMP="$(mktemp -d)"
readonly TEST_TEMP
TEST_SYSTEM_ROOT="${TEST_TEMP}/system"
readonly TEST_SYSTEM_ROOT
trap 'rm -rf -- "$TEST_TEMP"' EXIT

export VPSCTL_TESTING=1 VPSCTL_SYSTEM_ROOT="$TEST_SYSTEM_ROOT"
export VPSCTL_ENV_KERNEL_NAME=Linux VPSCTL_ENV_PACKAGE_MANAGER=apt-get
export VPSCTL_ENV_OS_ID=debian VPSCTL_ENV_OS_VERSION_ID=13
export VPSCTL_ENV_OS_VERSION='13 (trixie)' VPSCTL_ENV_OS_CODENAME=trixie
export VPSCTL_ENV_ARCH=x86_64 VPSCTL_ENV_VIRTUALIZATION=kvm
export VPSCTL_NON_INTERACTIVE=1 VPSCTL_NO_COLOR=1 VPSCTL_DRY_RUN=0

# shellcheck source=../../commands/system/kernel.sh
source "$TEST_ROOT/commands/system/kernel.sh"

declare -Ag KERNEL_GRUB_INSTALL_EXPECTED_VERSIONS KERNEL_RELEASE_COMPLETE
declare -Ag KERNEL_RELEASE_MANAGED KERNEL_RELEASE_PACKAGES KERNEL_PKG_STATUS KERNEL_PKG_VERSION

test_fail() {
    printf 'FAIL: %s\n' "$1" >&2
    exit 1
}

assert_equal() {
    [[ "$1" == "$2" ]] || test_fail "$3: expected '$1', got '$2'"
}

assert_contains() {
    [[ "$1" == *"$2"* ]] || test_fail "$3: missing '$2' in '$1'"
}

assert_status() {
    local expected="$1" message="$2" status=0
    shift 2
    "$@" >"$TEST_TEMP/last-output" 2>&1 || status=$?
    assert_equal "$expected" "$status" "$message ($(cat "$TEST_TEMP/last-output"))"
}

assert_rejected() {
    local message="$1" status=0
    shift
    "$@" >"$TEST_TEMP/last-output" 2>&1 || status=$?
    ((status != 0)) || test_fail "$message: unsafe fixture was accepted"
}

reset_fixture() {
    rm -rf -- "$TEST_SYSTEM_ROOT"
    mkdir -p "$TEST_SYSTEM_ROOT/etc/default/grub.d" \
        "$TEST_SYSTEM_ROOT/boot/grub/i386-pc" \
        "$TEST_SYSTEM_ROOT/var/lib/vpsctl/system/kernel" \
        "$TEST_SYSTEM_ROOT/proc" "$TEST_SYSTEM_ROOT/run/vpsctl"
    printf 'ID=debian\nVERSION_ID=13\nVERSION="13 (trixie)"\nVERSION_CODENAME=trixie\n' >"$TEST_SYSTEM_ROOT/etc/os-release"
    vps_cmd_init system-kernel-grub-install "$TEST_ROOT"
    kernel_init_paths
    KERNEL_OS_ID=debian
    KERNEL_OS_VERSION_ID=13
    KERNEL_OS_VERSION='13 (trixie)'
    KERNEL_OS_CODENAME=trixie
    KERNEL_ARCH=x86_64
    KERNEL_VIRTUALIZATION=kvm
    KERNEL_RUNNING_RELEASE=6.12.12-amd64
    KERNEL_GRUB_DISK=/dev/vda
    KERNEL_CONFIRM_INSTALL_GRUB=INSTALL-BIOS-GRUB
    KERNEL_GRUB_SUPPORTED=0
    VPSCTL_DRY_RUN=0
    VPSCTL_ASSUME_YES=0
    KERNEL_RELEASES=(7.2.4-x64v3-xanmod1 6.12.12-amd64)
    KERNEL_RELEASE_COMPLETE=(["7.2.4-x64v3-xanmod1"]=1 ["6.12.12-amd64"]=1)
    KERNEL_RELEASE_MANAGED=(["7.2.4-x64v3-xanmod1"]=1 ["6.12.12-amd64"]=1)
    KERNEL_RELEASE_PACKAGES=(["7.2.4-x64v3-xanmod1"]=linux-image-7.2.4-x64v3-xanmod1 ["6.12.12-amd64"]=linux-image-6.12.12-amd64)
    KERNEL_PKG_STATUS=()
    KERNEL_PKG_VERSION=()
    write_grub_fixture 0
}

write_grub_fixture() {
    local selector="$1" release
    printf "GRUB_DEFAULT='%s'\nGRUB_SAVEDEFAULT=false\n" "$selector" >"$KERNEL_GRUB_DEFAULT_FILE"
    cat >"$KERNEL_GRUB_CFG" <<EOF
# DO NOT EDIT THIS FILE
# generated by grub-mkconfig
set default="$selector"
### BEGIN /etc/grub.d/10_linux ###
menuentry 'Debian GNU/Linux' \$menuentry_id_option 'gnulinux-simple-UUID' {
    linux /boot/vmlinuz-7.2.4-x64v3-xanmod1 root=UUID=root-a ro
}
submenu 'Advanced options for Debian GNU/Linux' \$menuentry_id_option 'gnulinux-advanced-UUID' {
    menuentry 'Debian GNU/Linux, with Linux 7.2.4-x64v3-xanmod1' \$menuentry_id_option 'gnulinux-7.2.4-x64v3-xanmod1-advanced-UUID' {
        linux /boot/vmlinuz-7.2.4-x64v3-xanmod1 root=UUID=root-a ro
    }
    menuentry 'Debian GNU/Linux, with Linux 6.12.12-amd64' \$menuentry_id_option 'gnulinux-6.12.12-amd64-advanced-UUID' {
        linux /boot/vmlinuz-6.12.12-amd64 root=UUID=root-a ro
    }
}
### END /etc/grub.d/10_linux ###
EOF
    write_env_fixture
    for release in "${KERNEL_RELEASES[@]}"; do
        mkdir -p "$KERNEL_MODULES_DIR/$release/kernel"
        printf 'fixture image %s\n' "$release" >"$KERNEL_BOOT_DIR/vmlinuz-$release"
        printf 'fixture initrd %s\n' "$release" >"$KERNEL_BOOT_DIR/initrd.img-$release"
        printf 'fixture module\n' >"$KERNEL_MODULES_DIR/$release/kernel/test.ko"
    done
}

write_env_fixture() {
    python3 - "$KERNEL_GRUB_ENV" "$@" <<'PY'
import sys

content = ("# GRUB Environment Block\n" + "".join(line + "\n" for line in sys.argv[2:])).encode()
assert len(content) < 1024
with open(sys.argv[1], "wb") as stream:
    stream.write(content + b"#" * (1024 - len(content)))
PY
}

# JSON resembles util-linux output. The fixture mutates evidence only; all
# acceptance/rejection decisions remain in the production Python parser.
disk_fixture_field() {
    python3 - "$1" "$2" <<'PY'
import json
import sys

case, field = sys.argv[1:]
root = {"filesystems": [{"source": "/dev/vda1", "target": "/", "fstype": "ext4", "options": "rw,relatime", "maj:min": "252:1"}]}
boot = json.loads(json.dumps(root))
part = {"name": "/dev/vda1", "path": "/dev/vda1", "type": "part", "pkname": "/dev/vda", "maj:min": "252:1", "size": 8388608, "ro": False, "fstype": "ext4", "mountpoints": ["/"], "start": 2048, "parttype": "0x83"}
disk = {"name": "/dev/vda", "path": "/dev/vda", "type": "disk", "pkname": None, "maj:min": "252:0", "size": 16777216, "ro": False, "log-sec": 512, "pttype": "dos", "ptuuid": "0x12345678", "serial": "fixture-root", "wwn": None, "mountpoints": [None], "children": [part]}
lsblk = {"blockdevices": [disk]}
table = {"partitiontable": {"label": "dos", "id": "0x12345678", "device": "/dev/vda", "unit": "sectors", "sectorsize": 512, "partitions": [{"node": "/dev/vda1", "start": 2048, "size": 16384, "type": "83", "bootable": True}]}}
mbr = bytearray(512)
mbr[510:512] = bytes.fromhex("55aa")
requested = "/dev/vda"

if case in {"separate-boot", "cross-disk", "gpt", "gpt-small", "gpt-mounted", "gpt-formatted", "gpt-missing", "gpt-duplicate", "gpt-data-out-of-bounds"}:
    part["size"] = 4194304
    table["partitiontable"]["partitions"][0]["size"] = 8192
if case in {"separate-boot", "cross-disk"}:
    boot["filesystems"][0].update(source="/dev/vda2", target="/boot", **{"maj:min": "252:2"})
    disk["children"].append({"name": "/dev/vda2", "path": "/dev/vda2", "type": "part", "pkname": "/dev/vda", "maj:min": "252:2", "size": 4194304, "ro": False, "fstype": "ext3", "mountpoints": ["/boot"], "start": 10240, "parttype": "0x83"})
    boot["filesystems"][0]["fstype"] = "ext3"
    table["partitiontable"]["partitions"].append({"node": "/dev/vda2", "start": 10240, "size": 8192, "type": "83"})
if case == "cross-disk":
    second_part = disk["children"].pop()
    second_part.update(name="/dev/vdb1", path="/dev/vdb1", pkname="/dev/vdb", **{"maj:min": "253:1"})
    second_disk = json.loads(json.dumps(disk))
    second_disk.update(name="/dev/vdb", path="/dev/vdb", serial="fixture-data", children=[second_part], **{"maj:min": "253:0"})
    lsblk["blockdevices"].append(second_disk)
    boot["filesystems"][0].update(source="/dev/vdb1", **{"maj:min": "253:1"})
if case.startswith("gpt"):
    disk["pttype"] = "gpt"
    disk["ptuuid"] = "11111111-2222-3333-4444-555555555555"
    table["partitiontable"].update(label="gpt", id=disk["ptuuid"], firstlba=34, lastlba=32734)
    table["partitiontable"]["partitions"][0]["type"] = "0FC63DAF-8483-4772-8E79-3D69D8477DE4"
    part["parttype"] = table["partitiontable"]["partitions"][0]["type"]
    bios = {"name": "/dev/vda2", "path": "/dev/vda2", "type": "part", "pkname": "/dev/vda", "maj:min": "252:2", "size": 1048576, "ro": False, "fstype": None, "mountpoints": [None], "start": 10240, "parttype": "21686148-6449-6E6F-744E-656564454649"}
    bios_table = {"node": "/dev/vda2", "start": 10240, "size": 2048, "type": bios["parttype"], "uuid": "99999999-2222-3333-4444-555555555555", "name": "BIOS boot"}
    disk["children"].append(bios)
    table["partitiontable"]["partitions"].append(bios_table)
    mbr[450] = 0xEE
    if case == "gpt-small":
        bios["size"] = 524288
        bios_table["size"] = 1024
    elif case == "gpt-mounted":
        bios["mountpoints"] = ["/mnt/unsafe"]
    elif case == "gpt-formatted":
        bios["fstype"] = "ext4"
    elif case == "gpt-missing":
        disk["children"].pop()
        table["partitiontable"]["partitions"].pop()
    elif case == "gpt-duplicate":
        extra = json.loads(json.dumps(bios))
        extra.update(name="/dev/vda3", path="/dev/vda3", start=14336, **{"maj:min": "252:3"})
        disk["children"].append(extra)
        table["partitiontable"]["partitions"].append({"node": "/dev/vda3", "start": 14336, "size": 2048, "type": bios["parttype"]})
    elif case == "gpt-data-out-of-bounds":
        bios_table["start"] = 32700
        bios["start"] = 32700
if case == "extra-data-disk":
    data = json.loads(json.dumps(disk))
    data.update(name="/dev/vdb", path="/dev/vdb", serial="fixture-data", children=[], **{"maj:min": "253:0"})
    lsblk["blockdevices"].append(data)
elif case == "wrong-disk":
    requested = "/dev/vdb"
elif case == "partition-target":
    requested = "/dev/vda1"
elif case == "readonly-disk":
    disk["ro"] = True
elif case == "readonly-root":
    root["filesystems"][0]["options"] = "ro,relatime"
elif case == "unsupported-fs":
    root["filesystems"][0]["fstype"] = part["fstype"] = "btrfs"
elif case == "lvm":
    part["type"] = "lvm"
elif case == "raid":
    disk["type"] = "raid1"
elif case == "crypt":
    part["type"] = "crypt"
elif case == "multipath":
    disk["type"] = "mpath"
elif case == "small-gap":
    part["start"] = table["partitiontable"]["partitions"][0]["start"] = 63
elif case == "table-disagreement":
    table["partitiontable"]["device"] = "/dev/vdb"
elif case == "missing-source":
    root["filesystems"][0]["source"] = "overlay"
    root["filesystems"][0]["maj:min"] = "0:7"
elif case == "ambiguous-root":
    root["filesystems"].append(dict(root["filesystems"][0]))
elif case == "nvme":
    requested = "/dev/nvme0n1"
    root["filesystems"][0]["source"] = boot["filesystems"][0]["source"] = "/dev/nvme0n1p1"
    disk.update(name=requested, path=requested)
    part.update(name="/dev/nvme0n1p1", path="/dev/nvme0n1p1", pkname=requested)
    table["partitiontable"]["device"] = requested
    table["partitiontable"]["partitions"][0]["node"] = "/dev/nvme0n1p1"
elif case == "bad-sector":
    disk["log-sec"] = table["partitiontable"]["sectorsize"] = 0

values = {"root": root, "boot": boot, "lsblk": lsblk, "table": table, "mbr": mbr.hex(), "requested": requested}
value = values[field]
print(json.dumps(value, separators=(",", ":")) if isinstance(value, dict) else value)
PY
}

load_disk_fixture() {
    local mode="$1"
    DISK_ROOT_JSON="$(disk_fixture_field "$mode" root)"
    DISK_BOOT_JSON="$(disk_fixture_field "$mode" boot)"
    DISK_LSBLK_JSON="$(disk_fixture_field "$mode" lsblk)"
    DISK_TABLE_JSON="$(disk_fixture_field "$mode" table)"
    DISK_MBR_HEX="$(disk_fixture_field "$mode" mbr)"
    DISK_REQUESTED="$(disk_fixture_field "$mode" requested)"
}

parse_disk_fixture() {
    _kernel_grub_install_parse_disk_data "$DISK_REQUESTED" "$DISK_ROOT_JSON" "$DISK_BOOT_JSON" \
        "$DISK_LSBLK_JSON" "$DISK_TABLE_JSON" "$DISK_MBR_HEX"
}

test_disk_json_safety() (
    local mode output
    for mode in mbr separate-boot extra-data-disk nvme gpt; do
        load_disk_fixture "$mode"
        output="$(parse_disk_fixture)" || test_fail "$mode valid disk layout rejected"
        assert_contains "$output" "$DISK_REQUESTED" "$mode retains the selected disk identity"
    done
    load_disk_fixture extra-data-disk
    output="$(_kernel_grub_install_parse_disk_data '' "$DISK_ROOT_JSON" "$DISK_BOOT_JSON" "$DISK_LSBLK_JSON")"
    assert_equal /dev/vda "$output" 'extra data disk does not obscure the root disk recommendation'

    for mode in wrong-disk partition-target readonly-disk readonly-root unsupported-fs lvm raid crypt \
        multipath cross-disk small-gap table-disagreement missing-source ambiguous-root bad-sector \
        gpt-small gpt-mounted gpt-formatted gpt-missing gpt-duplicate gpt-data-out-of-bounds; do
        load_disk_fixture "$mode"
        assert_rejected "$mode layout is refused before writes" parse_disk_fixture
    done
    load_disk_fixture mbr
    DISK_ROOT_JSON='{"filesystems":['
    assert_rejected 'malformed findmnt JSON is refused' parse_disk_fixture
    load_disk_fixture mbr
    DISK_LSBLK_JSON='{"blockdevices":null}'
    assert_rejected 'missing lsblk devices is refused' parse_disk_fixture
    load_disk_fixture mbr
    DISK_TABLE_JSON='{}'
    assert_rejected 'missing partition-table evidence is refused' parse_disk_fixture
)

test_default_and_next_repair_plan() (
    reset_fixture
    kernel_inventory_load() { return 0; }
    _kernel_grub_install_plan_defaults || test_fail 'valid default plan rejected'
    assert_equal 7.2.4-x64v3-xanmod1 "$KERNEL_GRUB_INSTALL_DEFAULT_RELEASE" 'existing default semantics preserved despite a different running kernel'
    assert_equal 0 "$KERNEL_GRUB_INSTALL_FALLBACK" 'resolvable default does not fall back'

    write_grub_fixture '1>1'
    write_env_fixture 'next_entry=0'
    _kernel_grub_install_plan_defaults || test_fail 'valid one-time override plan rejected'
    assert_equal 6.12.12-amd64 "$KERNEL_GRUB_INSTALL_DEFAULT_RELEASE" 'numeric submenu default preserves its target'
    assert_equal 7.2.4-x64v3-xanmod1 "$KERNEL_GRUB_INSTALL_NEXT_RELEASE" 'valid numeric one-time override preserves its target'
    assert_equal 0 "$KERNEL_GRUB_INSTALL_CLEAR_NEXT" 'valid override will be retained'

    write_grub_fixture '1>1'
    write_env_fixture 'next_entry=unknown-menu-entry'
    _kernel_grub_install_plan_defaults || test_fail 'unresolved override should produce a repair plan'
    assert_equal 6.12.12-amd64 "$KERNEL_GRUB_INSTALL_DEFAULT_RELEASE" 'valid default retained when only next override is broken'
    assert_equal 0 "$KERNEL_GRUB_INSTALL_FALLBACK" 'invalid next override does not unnecessarily change default'
    assert_equal 1 "$KERNEL_GRUB_INSTALL_CLEAR_NEXT" 'unresolvable override is explicitly scheduled for removal'

    write_grub_fixture missing-default
    write_env_fixture 'next_entry=0'
    _kernel_grub_install_plan_defaults || test_fail 'unknown default should explicitly fall back to complete running kernel'
    assert_equal 6.12.12-amd64 "$KERNEL_GRUB_INSTALL_DEFAULT_RELEASE" 'unknown default falls back to running kernel'
    assert_equal 1 "$KERNEL_GRUB_INSTALL_FALLBACK" 'fallback is exposed on confirmation plan'
    assert_equal 1 "$KERNEL_GRUB_INSTALL_CLEAR_NEXT" 'default fallback clears even a valid prior one-time override'

    KERNEL_RELEASE_COMPLETE["6.12.12-amd64"]=0
    assert_rejected 'incomplete running kernel cannot be a fallback boot target' _kernel_grub_install_plan_defaults
    KERNEL_RELEASE_COMPLETE["6.12.12-amd64"]=1
    write_grub_fixture 0
    printf 'GRUB_DEFAULT=foreign\n' >"$KERNEL_GRUB_DROPIN"
    assert_status 10 'unmanaged conflicting drop-in is not overwritten' _kernel_grub_install_validate_paths
)

test_apt_plan_trust_and_scope() (
    local test_apt_case=valid package output log="$TEST_TEMP/apt-grub-plan.log"
    reset_fixture
    : >"$log"
    apt-get() {
        local test_efi_version
        printf '%s\n' "$(kernel_join_values "$@")" >>"$log"
        case "${1:-}" in
            indextargets)
                printf '%s\n' \
                    'Description: https://deb.debian.org/debian trixie/main amd64 Packages' \
                    'Identifier: Packages' 'Codename: trixie' 'Suite: stable' 'Release: trixie' \
                    'Origin: Debian' 'Label: Debian'
                if [[ "$test_apt_case" == untrusted-index ]]; then printf 'Trusted: no\n'; else printf 'Trusted: yes\n'; fi
                printf '\n'
                ;;
            --simulate)
                [[ "$*" == *APT::Get::AutomaticRemove=false* && "$*" == *--no-remove* && "$*" == *--no-install-recommends* ]] || return 97
                case "$test_apt_case" in
                    failure) return 100 ;;
                    no-changes)
                        printf '0 upgraded, 0 newly installed, 0 to remove.\n'
                        return 0
                        ;;
                    removal)
                        printf 'Remv libc6 [2.41]\n'
                        return 0
                        ;;
                    orphan-conf)
                        printf 'Conf grub-common (2.12-9 Debian:13/stable [amd64])\n'
                        return 0
                        ;;
                esac
                for package in grub-common grub2-common grub-pc-bin grub-pc libefiboot1; do
                    [[ "$test_apt_case" != efi-modules-without-common || "$package" != grub-common ]] || continue
                    printf 'Inst %s (2.12-9 Debian:13/stable [amd64])\n' "$package"
                    printf 'Conf %s (2.12-9 Debian:13/stable [amd64])\n' "$package"
                done
                if [[ "$test_apt_case" == kernel-change ]]; then
                    printf 'Inst linux-image-6.12.14-amd64 (2.12-9 Debian:13/stable [amd64])\n'
                elif [[ "$test_apt_case" == efi-change ]]; then
                    printf 'Inst grub-efi-amd64 (2.12-9 Debian:13/stable [amd64])\n'
                fi
                if [[ "$test_apt_case" == efi-modules-* ]]; then
                    for package in grub-efi-amd64-bin grub-efi-amd64-unsigned; do
                        test_efi_version=2.12-9
                        if [[ "$test_apt_case" == efi-modules-bin-mismatch && "$package" == grub-efi-amd64-bin ]] ||
                            [[ "$test_apt_case" == efi-modules-unsigned-mismatch && "$package" == grub-efi-amd64-unsigned ]]; then
                            test_efi_version=2.12-10
                        fi
                        printf 'Inst %s (%s Debian:13/stable [amd64])\n' "$package" "$test_efi_version"
                        printf 'Conf %s (%s Debian:13/stable [amd64])\n' "$package" "$test_efi_version"
                    done
                    case "$test_apt_case" in
                        efi-modules-backend) printf 'Inst grub-efi-amd64 (2.12-9 Debian:13/stable [amd64])\n' ;;
                        efi-modules-signed) printf 'Inst grub-efi-amd64-signed (2.12-9 Debian:13/stable [amd64])\n' ;;
                        efi-modules-shim) printf 'Inst shim-signed (2.12-9 Debian:13/stable [amd64])\n' ;;
                    esac
                fi
                ;;
            *) test_fail "package planning attempted an unexpected APT operation: $*" ;;
        esac
    }
    apt-cache() {
        [[ "${1:-}" == policy ]] || return 97
        local queried="$2" source='https://deb.debian.org/debian trixie/main amd64 Packages' policy_version=2.12-9
        if [[ "$test_apt_case" == foreign-request && "$queried" == grub-pc ]] ||
            [[ "$test_apt_case" == foreign-dependency && "$queried" == libefiboot1 ]] ||
            [[ "$test_apt_case" == efi-modules-foreign && "$queried" == grub-efi-amd64-bin ]]; then
            source='https://foreign.example trixie/main amd64 Packages'
        fi
        if [[ "$test_apt_case" == efi-modules-bin-mismatch && "$queried" == grub-efi-amd64-bin ]] ||
            [[ "$test_apt_case" == efi-modules-unsigned-mismatch && "$queried" == grub-efi-amd64-unsigned ]]; then
            policy_version=2.12-10
        fi
        printf '%s:\n  Installed: (none)\n  Candidate: %s\n  Version table:\n     %s 500\n        500 %s\n' "$queried" "$policy_version" "$policy_version" "$source"
        if [[ "$test_apt_case" == mixed-dependency && "$queried" == libefiboot1 ]] ||
            [[ "$test_apt_case" == efi-modules-mixed && "$queried" == grub-efi-amd64-unsigned ]]; then
            printf '        500 https://foreign.example trixie/main amd64 Packages\n'
        fi
    }
    _kernel_grub_install_plan_packages || test_fail 'official GRUB and dependency plan rejected'
    assert_equal 5 "${#KERNEL_GRUB_INSTALL_ARGS[@]}" 'complete package and dependency change list exposed'
    assert_equal 2.12-9 "${KERNEL_GRUB_INSTALL_EXPECTED_VERSIONS[libefiboot1]}" 'dependency exact version retained for post-install verification'
    output="$(kernel_join_values "${KERNEL_GRUB_INSTALL_ARGS[@]}")"
    assert_contains "$output" 'grub-pc=2.12-9' 'grub-pc version pinned'
    assert_contains "$output" 'libefiboot1=2.12-9' 'dependency version pinned'

    for test_apt_case in foreign-request foreign-dependency mixed-dependency untrusted-index; do
        assert_rejected "$test_apt_case cannot authorize package installation" _kernel_grub_install_plan_packages
    done
    test_apt_case=removal
    assert_status 30 'APT removal operation rejected' _kernel_grub_install_plan_packages
    test_apt_case=orphan-conf
    assert_status 30 'unplanned dpkg configuration rejected' _kernel_grub_install_plan_packages
    test_apt_case=kernel-change
    assert_status 3 'GRUB transaction cannot change kernel packages' _kernel_grub_install_plan_packages
    test_apt_case=efi-change
    assert_status 3 'BIOS installation cannot replace another boot backend' _kernel_grub_install_plan_packages
    test_apt_case=failure
    assert_status 20 'failed APT simulation never becomes an install plan' _kernel_grub_install_plan_packages

    test_apt_case='efi-modules-valid'
    KERNEL_PKG_STATUS=(['grub-common']='ii ' ['grub-efi-amd64-bin']='ii ')
    KERNEL_PKG_VERSION=(['grub-common']=2.12-8 ['grub-efi-amd64-bin']=2.12-8)
    _kernel_grub_install_plan_packages || test_fail 'installed EFI modules may follow the necessary matching official grub-common upgrade'
    assert_equal 7 "${#KERNEL_GRUB_INSTALL_ARGS[@]}" 'complete plan includes the required EFI binary and unsigned dependency versions'
    assert_equal 2.12-9 "${KERNEL_GRUB_INSTALL_EXPECTED_VERSIONS['grub-efi-amd64-bin']}" 'existing EFI binary upgrade is pinned'
    assert_equal 2.12-9 "${KERNEL_GRUB_INSTALL_EXPECTED_VERSIONS['grub-efi-amd64-unsigned']}" 'official unsigned dependency matches its binary version'
    KERNEL_PKG_STATUS['grub-efi-amd64-bin']='hi '
    _kernel_grub_install_plan_packages || test_fail 'configured held EFI binary still proves an existing backend module package'
    KERNEL_PKG_STATUS['grub-efi-amd64-bin']='ii '
    for test_apt_case in efi-modules-foreign efi-modules-mixed; do
        assert_status 30 "$test_apt_case still requires every EFI module dependency to be trusted" _kernel_grub_install_plan_packages
    done
    for test_apt_case in efi-modules-backend efi-modules-signed efi-modules-shim \
        efi-modules-without-common efi-modules-bin-mismatch efi-modules-unsigned-mismatch; do
        assert_status 3 "$test_apt_case cannot use the narrow existing-module upgrade exception" _kernel_grub_install_plan_packages
    done
    test_apt_case='efi-modules-valid'
    KERNEL_PKG_VERSION['grub-efi-amd64-bin']=2.12-10
    assert_status 3 'EFI binary compatibility exception cannot authorize a downgrade' _kernel_grub_install_plan_packages
    KERNEL_PKG_VERSION['grub-efi-amd64-bin']=2.12-8
    KERNEL_PKG_STATUS['grub-efi-amd64-bin']='rc '
    assert_status 3 'residual EFI binary configuration is not an installed module package' _kernel_grub_install_plan_packages
    unset 'KERNEL_PKG_STATUS[grub-efi-amd64-bin]' 'KERNEL_PKG_VERSION[grub-efi-amd64-bin]'
    assert_status 3 'BIOS installation cannot introduce a new EFI binary backend' _kernel_grub_install_plan_packages

    test_apt_case=valid
    KERNEL_PKG_STATUS['grub-common']='ii '
    KERNEL_PKG_VERSION['grub-common']=2.12-10
    assert_status 3 'dependency downgrade rejected against installed package state' _kernel_grub_install_plan_packages
    KERNEL_PKG_STATUS=(['grub-pc']='ii ')
    KERNEL_PKG_VERSION=(['grub-pc']=2.12-8)
    test_apt_case=no-changes
    : >"$log"
    _kernel_grub_install_plan_packages || test_fail 'already installed GRUB repair plan rejected'
    assert_equal 0 "${#KERNEL_GRUB_INSTALL_ARGS[@]}" 'repair does not automatically upgrade installed grub-pc'
    assert_equal 2.12-8 "${KERNEL_GRUB_INSTALL_EXPECTED_VERSIONS['grub-pc']}" 'repair retains currently installed version'
    assert_contains "$(<"$log")" 'grub-pc=2.12-8' 'repair simulation pins the installed version despite a newer candidate'
)

test_transaction_write_boundaries() (
    local mode=success prepare_count=0 status output log="$TEST_TEMP/grub-transaction.log"
    reset_fixture
    vps_cmd_require_root() { return 0; }
    kernel_take_lock() { printf 'lock\n' >>"$log"; }
    kernel_cleanup() { printf 'cleanup\n' >>"$log"; }
    kernel_confirm_action() {
        printf 'confirm\n' >>"$log"
        [[ "$mode" != cancel ]] || return 130
    }
    _kernel_grub_install_prepare() {
        prepare_count=$((prepare_count + 1))
        printf 'prepare:%s\n' "$prepare_count" >>"$log"
        KERNEL_GRUB_INSTALL_DISK=/dev/vda
        KERNEL_GRUB_INSTALL_PLAN_SIGNATURE=baseline
        KERNEL_GRUB_INSTALL_DEFAULT_RELEASE=6.12.12-amd64
        if [[ "$mode" == confirm-drift ]] && ((prepare_count >= 2)); then
            KERNEL_GRUB_INSTALL_PLAN_SIGNATURE=changed
        elif [[ "$mode" == backup-drift ]] && ((prepare_count >= 3)); then
            KERNEL_GRUB_INSTALL_PLAN_SIGNATURE=changed
        fi
    }
    _kernel_grub_install_show_plan() { printf 'fixture complete plan\n'; }
    _kernel_grub_install_backup() {
        printf 'backup\n' >>"$log"
        [[ "$mode" != backup-failure ]] || return 20
        KERNEL_GRUB_INSTALL_BACKUP="$TEST_TEMP/transaction-$mode"
        mkdir -p "$KERNEL_GRUB_INSTALL_BACKUP"
        printf 'backup-complete\n' >"$KERNEL_GRUB_INSTALL_BACKUP/stage"
        printf 'fixture recovery evidence\n' >"$KERNEL_GRUB_INSTALL_BACKUP/RECOVERY.txt"
    }
    _kernel_grub_install_execute() {
        printf 'execute\n' >>"$log"
        [[ "$mode" != install-failure ]] || return 20
        if [[ "$mode" == interrupted ]]; then
            # Signal only the currently running fixture transaction subshell.
            kill -TERM "$BASHPID"
            return 99
        fi
        printf 'complete-pending-reboot\n' >"$KERNEL_GRUB_INSTALL_BACKUP/stage"
    }

    : >"$log"
    VPSCTL_DRY_RUN=1
    output="$(kernel_install_grub 2>&1)" || test_fail 'dry-run failed'
    assert_equal 'prepare:1' "$(<"$log")" 'dry-run performs only read-only preparation'
    assert_contains "$output" '未刷新 APT' 'dry-run states zero-write behavior'
    [[ ! -e "$KERNEL_GRUB_BACKUP_ROOT" ]] || test_fail 'dry-run created a backup directory'
    VPSCTL_DRY_RUN=0

    for mode in cancel confirm-drift backup-failure backup-drift install-failure interrupted success; do
        : >"$log"
        status=0
        output="$(kernel_install_grub 2>&1)" || status=$?
        case "$mode" in
            cancel)
                assert_equal 130 "$status" 'cancel returns before lock and backup'
                assert_equal $'prepare:1\nconfirm' "$(<"$log")" 'cancel does not prepare a mutation'
                ;;
            confirm-drift)
                assert_equal 3 "$status" 'confirmation-time drift rejected'
                assert_equal $'prepare:1\nconfirm\nlock\nprepare:2\ncleanup' "$(<"$log")" 'confirmation drift prevents backup and writes'
                ;;
            backup-failure)
                assert_equal 20 "$status" 'backup failure is pre-install failure'
                [[ "$(<"$log")" != *execute* ]] || test_fail 'backup failure reached package or disk writes'
                ;;
            backup-drift)
                assert_equal 3 "$status" 'backup-time drift rejected'
                [[ "$(<"$log")" != *execute* ]] || test_fail 'backup-time drift reached installation'
                [[ -f "$TEST_TEMP/transaction-$mode/RECOVERY.txt" ]] || test_fail 'backup-time drift discarded recovery evidence'
                ;;
            install-failure | interrupted)
                assert_equal 30 "$status" "$mode is partial completion once writes could have begun"
                assert_contains "$output" '部分完成' "$mode describes incomplete installation accurately"
                [[ -f "$TEST_TEMP/transaction-$mode/result" && -f "$TEST_TEMP/transaction-$mode/RECOVERY.txt" ]] || test_fail "$mode lost recovery evidence"
                ;;
            success)
                assert_equal 0 "$status" 'successful validated installation'
                assert_equal $'prepare:1\nconfirm\nlock\nprepare:2\nbackup\nprepare:3\nexecute\ncleanup' "$(<"$log")" 'complete backup and final drift check precede writes'
                assert_contains "$output" '待重启验证' 'success does not claim actual firmware boot verification'
                ;;
        esac
    done
)

test_backup_integrity_and_failure() (
    local mode=mbr file backup
    reset_fixture
    KERNEL_GRUB_INSTALL_DISK="$TEST_TEMP/fixture-disk.bin"
    KERNEL_GRUB_INSTALL_DISK_DATA='{"disk":"fixture-only"}'
    KERNEL_GRUB_INSTALL_TABLE_DATA='{"label":"dos","device":"fixture-only"}'
    KERNEL_GRUB_INSTALL_DEFAULT_RELEASE=6.12.12-amd64
    KERNEL_GRUB_INSTALL_NEXT_RELEASE=''
    KERNEL_GRUB_INSTALL_ARGS=(grub-pc=2.12-9)
    KERNEL_GRUB_INSTALL_REGION_LENGTH=1048576
    KERNEL_GRUB_INSTALL_REGION_OFFSET=0
    KERNEL_GRUB_INSTALL_LABEL=dos
    printf 'fixture normal module\n' >"$KERNEL_BOOT_DIR/grub/i386-pc/normal.mod"
    python3 - "$KERNEL_GRUB_INSTALL_DISK" <<'PY'
import sys
with open(sys.argv[1], "wb") as stream:
    stream.write(b"M" * 1048576 + b"G" * 1048576)
PY
    sfdisk() {
        [[ "${1:-}" == --dump && "${2:-}" == "$KERNEL_GRUB_INSTALL_DISK" ]] || return 97
        printf 'label: dos\ndevice: fixture-only\n'
    }
    dpkg-query() { printf 'ii \tgrub-pc-bin\t2.12-9\n'; }
    _kernel_grub_install_debconf_snapshot() {
        [[ "$mode" != debconf-failure ]] || return 3
        printf 'grub-pc/install_devices\n0 /dev/old-wrong-disk\n0 true\n'
        printf 'grub-pc/cloud_style_installation\n0 true\n0 true\n'
    }
    dd() {
        [[ "$mode" != raw-read-failure ]] || return 1
        command dd "$@"
    }
    df() {
        if [[ "$mode" == insufficient-space ]]; then
            printf 'Avail\n0\n'
        else
            command df "$@"
        fi
    }

    for mode in mbr gpt; do
        if [[ "$mode" == gpt ]]; then
            KERNEL_GRUB_INSTALL_LABEL=gpt
            KERNEL_GRUB_INSTALL_REGION_OFFSET=1048576
        fi
        _kernel_grub_install_backup || test_fail "$mode complete recovery backup failed"
        backup="$KERNEL_GRUB_INSTALL_BACKUP"
        assert_equal 700 "$(stat -c %a "$backup")" 'backup directory has restricted permissions'
        assert_equal backup-complete "$(<"$backup/stage")" 'backup completes before any installation stage'
        for file in grub-files.tar disk-layout.json partition-table.json partition-table.sfdisk packages.tsv debconf.txt disk-regions.tsv RECOVERY.txt SHA256SUMS; do
            [[ -s "$backup/$file" ]] || test_fail "$mode recovery evidence missing: $file"
        done
        (cd -- "$backup" && sha256sum --check --status SHA256SUMS) || test_fail "$mode backup integrity manifest failed"
        assert_contains "$(<"$backup/disk-regions.tsv")" "$KERNEL_GRUB_INSTALL_REGION_OFFSET" "$mode records exact raw region offset"
        assert_contains "$(<"$backup/disk-regions.tsv")" '1048576' "$mode records exact raw region length"
        assert_contains "$(<"$backup/debconf.txt")" '/dev/old-wrong-disk' 'original erroneous debconf target preserved as recovery evidence'
        assert_contains "$(<"$backup/debconf.txt")" $'grub-pc/cloud_style_installation\n0 true' 'original cloud auto-disk setting preserved as recovery evidence'
        python3 - "$backup" "$mode" <<'PY'
from pathlib import Path
import sys

backup, mode = Path(sys.argv[1]), sys.argv[2]
expected = b"M" if mode == "mbr" else b"G"
assert (backup / "embedding-region.bin").read_bytes() == expected * 1048576
if mode == "gpt":
    assert (backup / "protective-mbr.bin").read_bytes() == b"M" * 512
PY
    done

    mode=raw-read-failure
    assert_status 20 'failed raw region read cannot complete a backup' _kernel_grub_install_backup
    assert_equal backing-up "$(<"$KERNEL_GRUB_INSTALL_BACKUP/stage")" 'failed raw read never marks backup complete'
    mode=debconf-failure
    assert_status 20 'unreadable old debconf state prevents installation backup' _kernel_grub_install_backup
    mode=insufficient-space
    rm -rf -- "$KERNEL_GRUB_BACKUP_ROOT"
    assert_status 20 'insufficient free space stops before creating backup' _kernel_grub_install_backup
    [[ ! -e "$KERNEL_GRUB_BACKUP_ROOT" ]] || test_fail 'insufficient space created a misleading backup directory'
)

test_configuration_signature_and_path_guards() (
    local before after paths package
    reset_fixture
    KERNEL_GRUB_INSTALL_DEFAULT_RELEASE=6.12.12-amd64
    KERNEL_GRUB_INSTALL_NEXT_RELEASE=''
    KERNEL_GRUB_INSTALL_EXPECTED_VERSIONS=()
    paths="$(_kernel_grub_install_config_paths)"
    [[ "$paths" != *'/usr/lib/grub/x86_64-efi'* ]] || test_fail 'unmodified EFI modules were unnecessarily included in BIOS recovery scope'
    for package in grub-efi-amd64-bin grub-efi-amd64-unsigned; do
        KERNEL_GRUB_INSTALL_EXPECTED_VERSIONS=([$package]=2.12-9)
        paths="$(_kernel_grub_install_config_paths)"
        assert_contains "$paths" "$TEST_SYSTEM_ROOT/usr/lib/grub/x86_64-efi" "$package changes include existing EFI modules in the pre-write backup"
    done
    KERNEL_GRUB_INSTALL_EXPECTED_VERSIONS=()
    _kernel_grub_install_validate_paths || test_fail 'safe fixture configuration paths rejected'
    before="$(_kernel_grub_install_config_signature)" || test_fail 'safe configuration signature rejected'
    printf 'changed boot image\n' >>"$KERNEL_BOOT_DIR/vmlinuz-6.12.12-amd64"
    after="$(_kernel_grub_install_config_signature)" || test_fail 'modified safe image signature rejected'
    [[ "$before" != "$after" ]] || test_fail 'boot image change is absent from confirmation drift signature'
    mkdir -p "$TEST_SYSTEM_ROOT/etc/apt/sources.list.d"
    printf 'deb https://deb.debian.org/debian trixie main\n' >"$TEST_SYSTEM_ROOT/etc/apt/sources.list.d/fixture.list"
    before="$(_kernel_grub_install_config_signature)"
    printf 'deb https://foreign.example trixie main\n' >>"$TEST_SYSTEM_ROOT/etc/apt/sources.list.d/fixture.list"
    after="$(_kernel_grub_install_config_signature)"
    [[ "$before" != "$after" ]] || test_fail 'APT source change is absent from confirmation drift signature'
    chmod 0666 "$KERNEL_BOOT_DIR/vmlinuz-6.12.12-amd64"
    assert_status 3 'writable-by-others boot image rejected from secure signature' _kernel_grub_install_config_signature
    chmod 0644 "$KERNEL_BOOT_DIR/vmlinuz-6.12.12-amd64"
    ln -s "$KERNEL_GRUB_DEFAULT_FILE" "$KERNEL_GRUB_DEFAULT_DIR/50-linked.cfg"
    assert_status 10 'symlink GRUB drop-in rejected' _kernel_grub_install_validate_paths
    rm -- "$KERNEL_GRUB_DEFAULT_DIR/50-linked.cfg"
    printf 'GRUB_DEFAULT=0\n' >"$KERNEL_GRUB_DEFAULT_DIR/zz-foreign.cfg"
    assert_status 10 'later unowned default override rejected before installing' _kernel_grub_install_validate_paths
    rm -- "$KERNEL_GRUB_DEFAULT_DIR/zz-foreign.cfg"
    printf 'readonly GRUB_DEFAULT=0\n' >"$KERNEL_GRUB_DEFAULT_FILE"
    assert_status 10 'readonly default cannot be silently overridden by a drop-in' _kernel_grub_install_validate_paths
    printf 'GRUB_DEFAULT=0\n' >"$KERNEL_GRUB_DEFAULT_FILE"
    printf 'corrupt environment\n' >"$KERNEL_GRUB_ENV"
    assert_status 10 'damaged environment block must be repaired before disk writes' _kernel_grub_install_validate_paths
    write_env_fixture 'next_entry=0' 'next_entry=1>1'
    assert_status 10 'duplicate environment variables rejected before backing up a mutation' _kernel_grub_install_validate_paths
    write_env_fixture
    printf 'file occupying directory\n' >"$KERNEL_GRUB_BACKUP_ROOT"
    assert_status 10 'ordinary file cannot occupy the backup directory path' _kernel_grub_install_validate_paths
)

test_execute_debconf_isolation_and_readback() (
    local test_execute_case=success package updates=0 status log="$TEST_TEMP/grub-execute.log" seed="$TEST_TEMP/debconf-current" output
    local expected_next='gnulinux-advanced-UUID>gnulinux-7.2.4-x64v3-xanmod1-advanced-UUID'
    local expected_default='gnulinux-advanced-UUID>gnulinux-6.12.12-amd64-advanced-UUID'
    kernel_inventory_load() { return 0; }
    kernel_grub_probe_active() { return 0; }
    # These names satisfy the post-install tool gate. The execution dispatcher
    # below intercepts every mutating command and uses only fixture files.
    grub-install() { test_fail 'unit test reached a real disk writer'; }
    update-grub() { test_fail 'unit test reached a host GRUB generator'; }
    grub-editenv() {
        [[ "${2:-}" == list ]] || test_fail 'unexpected direct environment write'
        [[ "$(stat -c %s "$1")" == 1024 ]]
    }
    debconf-set-selections() {
        cat >"$seed"
        if grep -Fqx 'grub-pc grub-pc/install_devices_empty boolean true' "$seed"; then
            printf 'seed:suppress\n' >>"$log"
        else
            printf 'seed:persist\n' >>"$log"
        fi
    }
    debconf-communicate() {
        local request question value
        request="$(cat)"
        [[ "$request" == 'GET grub-pc/'* ]] || return 97
        question="${request#GET }"
        value="$(awk -v question="$question" '$2 == question && ($3 == "multiselect" || $3 == "boolean") {sub(/^[^ ]+ [^ ]+ [^ ]+ /, ""); print; exit}' "$seed")"
        if [[ "$test_execute_case" == debconf-drift && "$question" == grub-pc/install_devices ]]; then
            printf '0 /dev/old-wrong-disk\n'
        elif [[ "$test_execute_case" == debconf-flag-drift && "$question" == grub-pc/install_devices_failed_upgrade ]]; then
            printf '0 true\n'
        elif [[ "$test_execute_case" == cloud-auto-drift && "$question" == grub-pc/cloud_style_installation ]]; then
            printf '0 true\n'
        else
            printf '0 %s\n' "$value"
        fi
    }
    _kernel_grub_install_probe_disk() {
        assert_equal /dev/vda "$1" 'post-install disk inspection uses confirmed device'
        [[ "$test_execute_case" != table-drift ]] || KERNEL_GRUB_INSTALL_TABLE_DATA=changed
    }
    _kernel_grub_install_run() {
        local argument selected=0
        case "$1" in
            env)
                printf 'apt\n' >>"$log"
                grep -Fqx 'grub-pc grub-pc/install_devices multiselect ' "$seed" || test_fail 'package hooks retained an old install disk'
                grep -Fqx 'grub-pc grub-pc/install_devices_disks_changed multiselect ' "$seed" || test_fail 'package hooks retained a changed-disk fallback'
                grep -Fqx 'grub-pc grub-pc/install_devices_empty boolean true' "$seed" || test_fail 'package hooks may prompt or write a guessed disk'
                grep -Fqx 'grub-pc grub-pc/install_devices_failed boolean false' "$seed" || test_fail 'package hook failures may be ignored'
                grep -Fqx 'grub-pc grub-pc/cloud_style_installation boolean false' "$seed" || test_fail 'Ubuntu cloud package hooks may bypass explicit install_devices'
                [[ "$test_execute_case" != apt-failure ]] || return 100
                [[ "$test_execute_case" != boot-drift ]] || printf 'unexpected initrd replacement\n' >>"$KERNEL_BOOT_DIR/initrd.img-6.12.12-amd64"
                ;;
            grub-install)
                printf 'disk:%s\n' "${!#}" >>"$log"
                assert_equal /dev/vda "${!#}" 'explicit GRUB installation targets only the confirmed disk'
                for argument in "$@"; do
                    [[ "$argument" != --force && "$argument" != --force=* ]] || test_fail 'explicit GRUB installation permits blocklist forcing'
                done
                [[ "$test_execute_case" != grub-failure ]] || return 1
                ;;
            update-grub)
                printf 'update\n' >>"$log"
                updates=$((updates + 1))
                if [[ -f "$KERNEL_GRUB_DROPIN" ]]; then
                    selected="$(sed -n "s/^GRUB_DEFAULT='\(.*\)'$/\1/p" "$KERNEL_GRUB_DROPIN")"
                fi
                [[ "$test_execute_case" != readback-failure || "$updates" != 2 ]] || selected=0
                sed -i "s|^set default=.*|set default=\"$selected\"|" "$KERNEL_GRUB_CFG"
                ;;
            grub-editenv)
                assert_equal "$KERNEL_GRUB_ENV" "$2" 'environment command targets fixture-owned path'
                printf 'env:%s\n' "$3" >>"$log"
                case "$3" in
                    create | unset) write_env_fixture ;;
                    set) write_env_fixture "$4" ;;
                    *) return 97 ;;
                esac
                ;;
            *) test_fail "unexpected mutating command in BIOS GRUB transaction: $1" ;;
        esac
    }

    for test_execute_case in success missing-env apt-failure grub-failure readback-failure table-drift debconf-drift debconf-flag-drift cloud-auto-drift boot-drift; do
        reset_fixture
        : >"$log"
        updates=0
        printf 'grub-pc grub-pc/install_devices multiselect /dev/old-wrong-disk\n' >"$seed"
        printf 'grub-pc grub-pc/cloud_style_installation boolean true\n' >>"$seed"
        KERNEL_GRUB_INSTALL_DISK=/dev/vda
        KERNEL_GRUB_INSTALL_TABLE_DATA=unchanged
        KERNEL_GRUB_INSTALL_BACKUP="$KERNEL_GRUB_BACKUP_ROOT/execute-fixture"
        mkdir -p "$KERNEL_GRUB_INSTALL_BACKUP"
        KERNEL_GRUB_INSTALL_ARGS=(grub-pc=2.12-9)
        KERNEL_GRUB_INSTALL_EXPECTED_VERSIONS=(['grub-pc']=2.12-9)
        for package in grub-pc grub-pc-bin grub-common grub2-common; do
            KERNEL_PKG_STATUS[$package]='ii '
            KERNEL_PKG_VERSION[$package]=2.12-9
        done
        printf 'fixture normal module\n' >"$KERNEL_BOOT_DIR/grub/i386-pc/normal.mod"
        write_grub_fixture '1>1'
        write_env_fixture 'next_entry=0'
        if [[ "$test_execute_case" == missing-env ]]; then rm -- "$KERNEL_GRUB_ENV"; fi
        _kernel_grub_install_plan_defaults || test_fail 'execute fixture default plan rejected'
        KERNEL_GRUB_INSTALL_PROTECTED_RELEASES=(6.12.12-amd64 7.2.4-x64v3-xanmod1)
        KERNEL_GRUB_INSTALL_BOOT_SIGNATURE="$(_kernel_grub_install_boot_signature)" || test_fail 'execute fixture boot signature failed'
        status=0
        output="$(_kernel_grub_install_execute 2>&1)" || status=$?
        if [[ "$test_execute_case" == success || "$test_execute_case" == missing-env ]]; then
            assert_equal 0 "$status" "$test_execute_case exact write and readback transaction ($output)"
            assert_contains "$(<"$log")" $'seed:suppress\napt\ndisk:/dev/vda\nseed:persist' 'package implicit writes disabled before explicit disk installation'
            grep -Fqx 'grub-pc grub-pc/cloud_style_installation boolean false' "$seed" || test_fail 'persisting the selected disk re-enabled Ubuntu cloud auto-selection'
            grep -Fqx "GRUB_DEFAULT='$expected_default'" "$KERNEL_GRUB_DROPIN" || test_fail 'default was not fixed to the precise version entry'
            assert_equal complete-pending-reboot "$(<"$KERNEL_GRUB_INSTALL_BACKUP/stage")" 'post-write verification completes the transaction'
            if [[ "$test_execute_case" == success ]]; then
                assert_contains "$(<"$KERNEL_GRUB_ENV")" "next_entry=$expected_next" 'numeric/simple next override retained as the exact release entry'
            else
                assert_contains "$(<"$log")" 'env:create' 'absent environment created only in backed-up write phase'
                [[ "$(<"$KERNEL_GRUB_ENV")" != *next_entry=* ]] || test_fail 'absent environment unexpectedly acquired an override'
            fi
        else
            assert_equal 30 "$status" "$test_execute_case is detected as incomplete installation ($output)"
            if [[ "$test_execute_case" == apt-failure || "$test_execute_case" == debconf-drift || "$test_execute_case" == debconf-flag-drift || "$test_execute_case" == cloud-auto-drift ]]; then
                [[ "$(<"$log")" != *disk:* ]] || test_fail 'APT failure proceeded to writing a boot sector'
                if [[ "$test_execute_case" == cloud-auto-drift ]]; then
                    [[ "$(<"$log")" != *apt* ]] || test_fail 'Ubuntu cloud auto-disk setting drift reached package scripts'
                fi
            elif [[ "$test_execute_case" == grub-failure ]]; then
                [[ "$(<"$log")" != *seed:persist* ]] || test_fail 'failed boot sector install persisted an unverified target'
            fi
        fi
    done
)

test_platform_evidence_gates() (
    local mode=valid disabled missing_tool=''
    reset_fixture
    mkdir -p "$TEST_SYSTEM_ROOT/sys/class/dmi/id"
    printf 'SeaBIOS fixture\n' >"$TEST_SYSTEM_ROOT/sys/class/dmi/id/bios_vendor"
    printf 'CONFIG_EFI=y\n' >"$KERNEL_BOOT_DIR/config-$KERNEL_RUNNING_RELEASE"
    printf 'BOOT_IMAGE=/boot/vmlinuz-6.12.12-amd64 root=UUID=root-a ro\n' >"$TEST_SYSTEM_ROOT/proc/cmdline"
    command() {
        [[ "${1:-}" != -v || "${2:-}" != "$missing_tool" ]] || return 1
        builtin command "$@"
    }
    sfdisk() { return 97; }
    blkid() { return 97; }
    blockdev() { return 97; }
    debconf-communicate() { return 97; }
    debconf-set-selections() { test_fail 'platform check wrote debconf'; }
    apt-get() { test_fail 'platform check attempted an APT operation'; }
    apt-cache() { return 97; }
    dpkg-query() { return 97; }
    systemd-detect-virt() {
        [[ "$mode" == container && "${1:-}" == --container ]] && return 0
        [[ "$mode" == chroot && "${1:-}" == --chroot ]] && return 0
        return 1
    }
    findmnt() {
        if [[ "$mode" == incomplete-sysfs ]]; then printf 'tmpfs\n'; else printf 'sysfs\n'; fi
    }
    dpkg() {
        [[ "${1:-}" == --audit ]] || return 97
        [[ "$mode" != unfinished-dpkg ]] || printf 'grub-pc is only half configured\n'
    }
    assert_status 0 'BIOS evidence with EFI-capable kernel and complete sysfs accepted' _kernel_grub_install_require_platform
    for mode in container chroot incomplete-sysfs unfinished-dpkg; do
        assert_status 3 "$mode cannot install a bootloader" _kernel_grub_install_require_platform
    done
    mode=valid
    KERNEL_ARCH=aarch64
    assert_status 3 'non-amd64 platform rejected' _kernel_grub_install_require_platform
    KERNEL_ARCH=x86_64
    mkdir -p "$TEST_SYSTEM_ROOT/sys/firmware/efi"
    assert_status 3 'UEFI installation rejected' _kernel_grub_install_require_platform
    rmdir "$TEST_SYSTEM_ROOT/sys/firmware/efi"
    for disabled in noefi efi=disable efi=noruntime; do
        printf 'root=UUID=root-a %s ro\n' "$disabled" >"$TEST_SYSTEM_ROOT/proc/cmdline"
        assert_status 3 "$disabled cannot make an EFI machine look like BIOS" _kernel_grub_install_require_platform
    done
    printf 'root=UUID=root-a ro\n' >"$TEST_SYSTEM_ROOT/proc/cmdline"
    rm -- "$TEST_SYSTEM_ROOT/sys/class/dmi/id/bios_vendor"
    assert_status 3 'missing DMI BIOS evidence rejected' _kernel_grub_install_require_platform
    printf 'SeaBIOS fixture\n' >"$TEST_SYSTEM_ROOT/sys/class/dmi/id/bios_vendor"
    printf '# CONFIG_EFI is not set\n' >"$KERNEL_BOOT_DIR/config-$KERNEL_RUNNING_RELEASE"
    assert_status 3 'EFI-disabled running kernel is insufficient evidence for BIOS mode' _kernel_grub_install_require_platform
    printf 'CONFIG_EFI=y\n' >"$KERNEL_BOOT_DIR/config-$KERNEL_RUNNING_RELEASE"
    printf 'legacy bootloader\n' >"$KERNEL_BOOT_DIR/grub/menu.lst"
    assert_status 3 'GRUB Legacy migration refused' _kernel_grub_install_require_platform
    rm -- "$KERNEL_BOOT_DIR/grub/menu.lst"
    missing_tool=python3
    assert_status 3 'missing inspection dependency is not silently installed with GRUB' _kernel_grub_install_require_platform
    assert_contains "$(<"$TEST_TEMP/last-output")" 'python3' 'missing inspection dependency named in diagnostic'
)

test_debconf_snapshot_is_read_only() (
    local mode=registered output log="$TEST_TEMP/debconf-reads.log"
    reset_fixture
    : >"$log"
    debconf-communicate() {
        local request
        request="$(cat)"
        printf '%s\n' "$request" >>"$log"
        [[ "$request" == GET* && "$request" == *FGET* ]] || test_fail 'snapshot attempted something other than question reads'
        if [[ "$mode" == absent ]]; then
            printf '10 question does not exist\n10 question does not exist\n'
            return 10
        elif [[ "$mode" == failure ]]; then
            printf '100 database unavailable\n'
            return 1
        fi
        if [[ "$request" == 'GET grub-pc/cloud_style_installation'* ]]; then
            printf '0 true\n0 true\n'
        else
            printf '0 /dev/old-wrong-disk\n0 true\n'
        fi
    }
    output="$(_kernel_grub_install_debconf_snapshot)" || test_fail 'registered debconf questions could not be snapshotted'
    assert_contains "$output" '/dev/old-wrong-disk' 'snapshot preserves prior target for recovery'
    assert_contains "$output" 'grub-pc/install_devices_failed_upgrade' 'snapshot includes failure handling configuration'
    assert_contains "$output" $'grub-pc/cloud_style_installation\n0 true\n0 true' 'snapshot preserves Ubuntu cloud auto-selection value and seen state'
    [[ "$(<"$log")" != *SET* && "$(<"$log")" != *REGISTER* ]] || test_fail 'read-only snapshot modified the debconf database'
    mode=absent
    output="$(_kernel_grub_install_debconf_snapshot)" || test_fail 'absent grub-pc questions should not require package installation'
    assert_contains "$output" '10 question does not exist' 'snapshot distinguishes absent questions'
    mode=failure
    assert_status 3 'unreadable debconf database prevents a complete backup plan' _kernel_grub_install_debconf_snapshot
)

printf 'TEST: BIOS GRUB disk JSON safety\n'
test_disk_json_safety
printf 'TEST: BIOS GRUB default and next override repair planning\n'
test_default_and_next_repair_plan
printf 'TEST: BIOS GRUB APT trust and transaction scope\n'
test_apt_plan_trust_and_scope
printf 'TEST: BIOS GRUB write boundaries, drift and interruption\n'
test_transaction_write_boundaries
printf 'TEST: BIOS GRUB recovery backup integrity and failure\n'
test_backup_integrity_and_failure
printf 'TEST: BIOS GRUB configuration drift and path safety\n'
test_configuration_signature_and_path_guards
printf 'TEST: BIOS GRUB debconf isolation and post-write verification\n'
test_execute_debconf_isolation_and_readback
printf 'TEST: BIOS GRUB platform and firmware evidence\n'
test_platform_evidence_gates
printf 'TEST: BIOS GRUB read-only debconf snapshots\n'
test_debconf_snapshot_is_read_only
printf 'PASS: system kernel BIOS GRUB installation tests\n'
